### ISSUE TITLE
Possible performance drop with `Blame` functionality

### ISSUE THREAD

**Issue by ivansvlv** [sublimehq/sublime_merge#998] opened 2020-11-25 12:40 UTC
**Version info**

 - OS: macOS Big Sur 11.0.1
 - Build: 2041

**Description**

I'm not completely sure whether it's a performance **drop**, but it's the first time I've noticed slowness of SM. Opening file (React component `.tsx` ~200 lines of code) in "Blame", takes like up to 3 seconds to open it. Commit details that I can share are in the screenshot below. Commit was big, because of a lot of changes in `package-lock.json` file. To clarify, jumping between much smaller commits of the same file, was very fast as always, but each time I clicked on this bigger commit, it was quite slow.
**Note**: files in the commit were of the following type - `.tsx` and `.json`

**Steps to reproduce**

1. Open repository
2. Run command - `Blame...`
3. Click on commit, takes up to 3 seconds to view file from this specific commit.

**Expected behavior**

I'm not sure whether it's actually _slow_, but my experience was that it usually opens instantaneously. 

**Screenshots**

![image](https://user-images.githubusercontent.com/16175855/100228825-f1195300-2f2b-11eb-9b6e-1e65c2c71f89.png)

**Comment by dpjohnst** [comment] 2020-11-26 00:37
Hi @ivansvlv,

Thanks for reporting this!

I've managed to track down the cause of the issue, and I'm investigating it further.
I'll reach out again when we've resolved the issue.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment] 2021-01-29 05:20
Thanks for the feedback - this should be fixed in development build 2042. Let me know if you see further performance issues and I'll gladly investigate.

**Comment by ivansvlv** [comment] 2021-01-29 08:00
> Thanks for the feedback - this should be fixed in development build 2042. Let me know if you see further performance issues and I'll gladly investigate.

@dpjohnst thank you! looks like it's fixed indeed. I've opened some files from that huge commit, and it doesn't seem to freeze anymore.

**Comment by dpjohnst** [comment] 2021-02-23 22:39
Hi @ivansvlv,

Just following up that this was released to the stable channel (Sublime Merge Build 2047)

Cheers,
\- Dylan

**Closed by dpjohnst** 2021-02-23 22:39 UTC
Labels: performance
