### ISSUE TITLE
Filter working directory changed files list

### ISSUE THREAD

**Issue by safield** [sublimehq/sublime_merge#417] opened 2019-03-14 16:12 UTC
I would like a feature where I could filter the working directory.

I could have a large number of changed files, and I might want to view / discard a single file. This manual search can become tedious as the number of changed files increases.

It would also be nice if I could filter using regex (implicit or explicit).

So I could type *.xml or just .xml to see all the changed xml files in the working directory.

As a side note. I think the duality between the contents view and the larger right hand side changes view is cumbersome. For example, if the previously described feature were to be added.....where would it be added? Sublime Merge essentially has TWO "working directory changed files lists". Why? Prediction....as more and more behaviours are added to Sublime Merge, the confusion and complexity of these two common but different views will become more and more a hindrance.

**Comment by srbs** [comment] 2019-03-15 03:58
Duplicate of #330 with the exception of supporting regex based filtering.

**Comment by dpjohnst** [comment] 2020-12-04 06:20
Closing this issue as it's mostly a duplicate of #330 - feel free to head over to that issue and subscribe to it for status updates, and add a comment mentioning regex based filtering.

**Closed by dpjohnst** 2020-12-04 06:20 UTC
