### ISSUE TITLE
Mouse wheel not working on linux

### ISSUE THREAD

**Issue by ineol** [sublimehq/sublime_merge#282] opened 2018-12-01 17:09 UTC
**Version info**

 - OS: Debian testing
 - Build: 1092

**Description**

I'm on a thinkpad laptop, and two-finger scrolling does not work since I upgraded to 1092.

**Steps to reproduce**

1. Open repository
2. Try to scroll the list of commits

**Expected behavior**
The list should scroll

**Comment by srbs** [comment] 2018-12-01 20:51
Note: this has been [reported in Sublime Text](https://forum.sublimetext.com/t/build-3181-arch-linux-scroll-wheel-stopped-working/40672) as well and is likely caused by the GTK3 switch. Once identified & fixed, I imagine both projects will be fixed.

**Comment by jskinner** [comment] 2018-12-06 07:11
I believe this is fixed in builds 1095+

**Closed by jskinner** 2018-12-06 07:11 UTC

**Comment by ineol** [comment] 2018-12-06 16:24
It's fixed indeed, thanks!
