### ISSUE TITLE
Clear out repositories in "Switch Repository"

### ISSUE THREAD

**Issue by skarchmit** [sublimehq/sublime_merge#1112] opened 2021-04-02 18:54 UTC
**Problem description**

There's some repositories that I've removed off my computer, but when I do command + shift +  O to switch repositories, I still see those repositories. I currently dont have a way to clear out the ones I dont need anymore. 

**Preferred solution**

Opening the repository should give a pop up saying that this repository does not exist and give you an option to remove it

**Alternatives**

Have an option in settings to clear repositories in switch repositories. 
Tab or right click on the repository to show options like remove?

**Comment by stinos** [comment] 2021-04-03 06:36
>  I currently dont have a way to clear out the ones I dont need anymore

Can be done by manually removing them from the Session.sublime_session file (in `~/.config/sublime-merge/Local` on unix or `%APPDATA%/Sublime Merge/Local` on Windows). Not ideal :)

> Opening the repository should give a pop up saying that this repository does not exist and give you an option to remove it

What's the chance you're actually going to try to open a repository you don't have anymore though? I'd rather have  way to invoke this on demand, i.e. a menu item which leads to scanning all history entries and removing the ones which do not exist anymore. Also makes me wonder what the impact of never cleaning the file would be on startup time. It needs to be read and parsed, mine is now already 300kB, and only like 5% is effectively used, rest is from repositories I don't have anymore.

Anyway: duplicate of/related to #359 #641 and a bunch of others, so might be better to close this.

**Comment by Ultra-Instinct-05** [comment] 2021-04-03 08:32
So ST4 added a way to clear out dead projects using `Project -> Open Recent -> Clear Items`. Maybe something similar could be done for Merge (a new command maybe) to clear out dead repositories.

**Comment by dpjohnst** [comment] 2021-04-05 23:50
Hi @skarchmit,

Thanks for sharing this feedback!

As noted, this is a duplicate of https://github.com/sublimehq/sublime_merge/issues/359 (similar enough to that we can share that issue).

I'm going ahead and closing this issue, but feel free to give the linked issue a thumbs up or subscribe to it!

Thanks,
\- Dylan

**Closed by dpjohnst** 2021-04-05 23:50 UTC
