### ISSUE TITLE
Recently active branch disappears intermittently on branch switch

### ISSUE THREAD

**Issue by crowe00** [sublimehq/sublime_merge#529] opened 2019-06-27 18:19 UTC
**Version info**

 - OS: macOS 10.14.4
 - Build: Build 1116

**Description**

When changing (double clicking on) another branch the previously active branch disappears from the branch tree view

**Steps to reproduce**

1. Double click a branch in the Locations tab and wait for the switch to take place
2. Double click a different branch and wait again
3. Check the branch view and see that the 1st branch is now hidden (intermittent, more times than not though)

**Expected behavior**

My recently active branch should remain visible.

**Comment by srbs** [comment] 2019-06-27 20:38
This is likely caused by the `Merge Commit Display` feature when set to `Collapse by default`. It's exposed when switching to the different branch if the previous branch was merged into another or some other similar merge.

You shouldn't see this issue if you set that setting to `Expand by default`.

**Comment by crowe00** [comment] 2019-07-01 17:42
Seems to be working better now, I'll keep using it this way to see if it clears up my issue. Thanks!

**Closed** 2019-07-05 18:04 UTC
