### ISSUE TITLE
Add support for partial stash

### ISSUE THREAD

**Issue by japanese-goblinn** [sublimehq/sublime_merge#1507] opened 2022-06-01 18:44 UTC
**Problem description**

I'd like to have ability for partial stash, absence of this feature is a main blocker for me to fully switch to sublime merge

**Preferred solution**

I think [fork's](https://git-fork.com/) solution is pretty good (screenshots below) with some changes I think it can be integrated into sublime

**Screenshots**

<img width="508" alt="image" src="https://user-images.githubusercontent.com/33631005/171478664-556bf4af-118e-4f65-b6f3-61db3a7a4abf.png">
<img width="558" alt="image" src="https://user-images.githubusercontent.com/33631005/171478672-75ac09e5-e44a-4d84-9c8d-ad44d042fa4b.png">

**Comment by srbs** [comment] 2022-07-10 05:23
partial duplicate of #2 
probably requires some way to select multiple files: #381 (unless using file filters in `Files` pane)

**Comment by ravindUwU** [comment] 2023-10-06 05:11
> probably requires some way to select multiple files

Ctrl-clicking on items in the file list allows multiple selection 😄. On Windows, on build 2091 anyway 💁.

**Closed** 2024-04-28 17:11 UTC
