### ISSUE TITLE
Improve scrolling behaviour of status/console output

### ISSUE THREAD

**Issue by schnoddelbotz** [sublimehq/sublime_merge#343] opened 2019-01-11 13:07 UTC
**Problem description**

I'm using a pre-push git hook that runs tests. Its output contains some 'very' long lines, which causes horizontal scrollbars to always scroll to the right, making relevant output invisible.
Manually scrolling back to the left will be overridden as soon as new output gets added.

**Preferred solution**

Status window should always scroll to first column / left side to allow following the hook's output.

**Alternatives**

A preference setting that allows to control scrolling behaviour?
Potentially, let users disable horizontal scrolling completely by enabling line wrapping.

**Screenshots**

![screenshot 2019-01-11 at 13 42 25](https://user-images.githubusercontent.com/2153919/51035359-0ee4a580-15aa-11e9-9dcc-595d95d157c9.png)

**Comment by willrowe** [comment] 2019-01-16 14:32
I'm seeing issues in the latest dev version with it not even allowing scrolling. If a line wider than the screen is displayed then the beginning and end of all lines are cut off with no ability to view them.

**Comment by willrowe** [comment] 2019-01-16 19:13
The specific issue that I referenced seems to have been fixed in build 1100.

**Comment by willrowe** [comment] 2019-05-22 17:35
This is still a major issue for me. As I previously stated, if the content is wider than the available space, it will not clip the right and left edges of the content, making it unreadable.

A horizontal scrollbar is available, but it will not scroll fully to the left or the right.

**Comment by davidbonnet** [comment] 2019-11-22 15:35
Due to this bug, I have to use a terminal. Thus it removes a lot of value… So close to perfection!

**Comment by alfredoreduarte** [comment] 2020-01-16 16:58
I'd also love it if you guys could ad a horizontal scrollbar to the console output.

<img width="1072" alt="Screen Shot 2020-01-16 at 1 52 45 PM" src="https://user-images.githubusercontent.com/4633753/72545728-41ce1300-3868-11ea-9fcb-b63a36d2a90c.png">

**Comment by willrowe** [comment] 2020-03-30 14:38
The issue with not being able to view all of the output when it is wide has been fixed in build 2002. However, it still automatically scrolls to the right when new output is added to the bottom, which means that you end up looking at nothing when new lines are shorter than previous lines and need to scroll back to the left in order to see it.

Automatically scrolling vertically is great, but doing so horizontally is not as useful.

**Comment by davidbonnet** [comment] 2020-05-26 11:24
Fixed in the version 2 of Sublime Merge. 🎉

**Comment by schnoddelbotz** [comment] 2020-05-26 14:49
@davidbonnet I really wanted to join the 🎉 ... but nope 👎 At least not on Mac.

Put this in your `.git/hooks/pre-push`:
```bash
for i in `seq 1 1000`; do
  date
  blah="blah $blah"
  echo "This sucks for ages now blah $blah"
  sleep 0.1
done
```

Then push via SublimeMerge and watch console cinema. Maybe it jumps around faster now, but still: just unreadable, impossible to follow output once lines get longer than console window width permits / line wraps occur.

And by adding loads of http:// links to the console output (like maven output in my real pre-push hook) SublimeMerge now used 18 GB RAM ... when I decided to kill the beast to make my machine respond again...
<img width="816" alt="smerge_mem" src="https://user-images.githubusercontent.com/2153919/82915134-ac0e6700-9f70-11ea-8ad4-f3a4a55734ed.png">
<img width="1171" alt="smerge_kill" src="https://user-images.githubusercontent.com/2153919/82915139-aca6fd80-9f70-11ea-8ad5-eb60e9f2df55.png">

**Comment by willrowe** [comment] 2020-05-27 13:00
I just tested this in build 2020 and the output is still scrolled horizontally to the right and does not scroll back when new lines are added. The other issues with long lines being clipped was already resolved, but this issue is related to the auto-scrolling. Preferred solution is to not scroll horizontally at all, but determining the length of each new line added to the output and scrolling to the end of it would also mitigate the issue.

**Comment by dpjohnst** [comment] 2020-06-30 08:14
Hi all,

I have identified the issue, and it will be fixed in the next build of Sublime Merge.
Thank you for your patience while this has been addressed.

Kind regards,
\- Dylan

**Comment by willrowe** [comment] 2020-07-20 17:57
I can confirm that this works as expected in build 2024.

**Comment by dpjohnst** [comment] 2020-07-21 03:00
I'm going to go ahead and close this issue as it's been fixed in development build 2024.

**Closed by dpjohnst** 2020-07-21 03:00 UTC
Labels: bug
