### ISSUE TITLE
Graphical artifacts on Mac OS

### ISSUE THREAD

**Issue by sbdchd** [sublimehq/sublime_merge#796] opened 2020-06-10 13:09 UTC
**Version info**

 - OS: macOS 10.15.4 (19E287)
 - Build: 2020

**Description**

Graphical artifacts when rendering

**Steps to reproduce**

1. Open a repository
2. Artifacts should be there but changing the commit message should make them more obvious

**Expected behavior**

No graphical artifacts

**Screenshots**

![sublime-artifacting](https://user-images.githubusercontent.com/7340772/84271280-e728a280-aaf9-11ea-89dd-e6ee8c09d5ec.gif)

^ short dark lines kind of flickering near the commit message

**Comment by dpjohnst** [comment] 2020-06-11 00:58
Hi @sbdchd,

Thanks for reporting this.

This is a duplicate of https://github.com/sublimehq/sublime_merge/issues/747
I'm going to go ahead and close this one, but free to subscribe to the linked issue to keep up to date with any progress.

Thanks,
\- Dylan

**Closed by dpjohnst** 2020-06-11 00:58 UTC
