### ISSUE TITLE
automatic "Fetch all" option for all repositories

### ISSUE THREAD

**Issue by pjanck** [sublimehq/sublime_merge#803] opened 2020-06-17 13:40 UTC
**Problem description**

I switched to SM from SourceTree. I really liked that Atlassian's SourceTree showed the amount of commits I'm behind on my local repo for *all* repositories whenever I started the program and even updated during the execution.

It bothers me that I need to switch through my open repositories and execute `fetch all` every time.

**Preferred solution**

I propose an option to execute `fetch all` for all opened repositories automatically at start / periodically / when pressing a button in UI. This should probably be optionally switched on/off in the settings for those not wishing for this feature to be executed. I imagine this being a preference customizable by the user (dropdown somewhere in the menus --> choose one of [at program start; periodically; never]), or within the settings file.

I don't see the need for the number in the repo's tab as SourceTree has it.

**Alternatives**

I don't see an alternative for the idea but am open to suggestions about the execution.

**Comment by dpjohnst** [comment] 2020-06-17 14:50
Hi @pjanck,

Thanks for sharing this suggestion with us.
As this is a duplicate of https://github.com/sublimehq/sublime_merge/issues/25, I'm going to go ahead and close it. Please feel free to subscribe to the linked issue so you can receive any updates to the issue.

Many thanks,
\- Dylan

**Closed by dpjohnst** 2020-06-17 14:50 UTC
