### ISSUE TITLE
Checkout File

### ISSUE THREAD

**Issue by TheClams** [sublimehq/sublime_merge#76] opened 2018-10-06 04:35 UTC
**Problem description**

There is currently no easy way (or I did not find it) to just checkout one file from a selected commit

**Preferred solution**

In the action menu for file modified in a commit add "reset file to this revision" and maybe "reset file to parents"

**Alternatives**

A similar option in the view tree would be great

**Comment by tkuraku** [comment] 2018-10-08 03:15
This is a duplicate of #23 .

**Closed** 2018-10-08 04:59 UTC
