### ISSUE TITLE
Tags on unmerged, but deleted branches are hidden

### ISSUE THREAD

**Issue by bferg88** [sublimehq/sublime_merge#771] opened 2020-06-01 20:00 UTC
**Version info**

 - OS: Ubuntu 18.04
 - Build: 2020

**Description**

Tags that point to unmerged branches that have been deleted do not show up in the graph.

**Steps to reproduce**

1. Create branch
2. Add a commit to branch
3. Tag branch
4. Delete branch
5. Observe absence of tag in the graph in sublime merge.

**Expected behavior**

I'd expect the tagged commit lineage to be displayed in the graph

**Comment by srbs** [comment] 2020-06-01 23:52
duplicate of #176

**Comment by dpjohnst** [comment] 2021-09-30 03:39
This was fixed in Sublime Merge Build 2038

**Closed by dpjohnst** 2021-09-30 03:39 UTC
Labels: bug, R: duplicate, S: minor
