### ISSUE TITLE
Crash on "Create Tag at Commit"

### ISSUE THREAD

**Issue by rusproject** [sublimehq/sublime_merge#1692] opened 2023-01-03 15:43 UTC
**Version info**

 - OS: Windows 10 21H2 LTSC
 - Build: 2079

**Description**

Sublime Merge spontaneously exit itself (I think it crashes) when I hit "Create Tag at Commit" at the commit

+ Git normally creates the tag from command line (git tag -a ... -m ...) on the same commit.
+ Sublime Merge normally creates the tag on other commits.

**Steps to reproduce**

I can't tell if it's reproducible on a random repo, but in our (it's private) repo the steps were:
1. Merge a branch to master with `--no-ff --no-commit` settings
2. Commit the merge
3. **Right click** on that commit
4. Click `Create Tag at Commit`

**Expected behavior**

Palette for adding tag is opened

**Screenshots**

I've captured a video with the problem:
https://user-images.githubusercontent.com/62891105/210390083-4cd32ce4-8233-4afa-942e-d0cbdaae442f.mp4

**Comment by dpjohnst** [comment] 2023-01-23 05:21
This was resolved in Sublime Merge build 2080 (development build), and will be fixed in the next stable build.
Closing as duplicate of: https://github.com/sublimehq/sublime_merge/issues/1647

**Closed by dpjohnst** 2023-01-23 05:21 UTC
