### ISSUE TITLE
Wrap command line output of git commands

### ISSUE THREAD

**Issue by sakekasi** [sublimehq/sublime_merge#538] opened 2019-07-10 19:35 UTC
**Problem description**

I have a precommit/prepush hook that has some very long lines in its output. When these lines come out, the command line output looks like it's forcibly scrolled to the right. 

**Preferred solution**

Wrap the command line output of commands so that the output fits in the window width

**Alternatives**

Allow scrolling of the command line output of commands

**Screenshots**

If applicable, add screenshots to help demonstrate the problem or proposed solution. This section may be omitted/removed.

<img width="1440" alt="Screenshot 2019-07-10 12 35 26" src="https://user-images.githubusercontent.com/979969/60999126-37f2b280-a30f-11e9-9633-a80e1b52e930.png">

**Comment by srbs** [comment] 2019-07-12 23:18
related: 343

**Comment by willrowe** [comment] 2019-07-14 20:33
As I have commented on the other issue, this really needs to be address. It causes a lot of the output to be inaccessible.

**Comment by davidbonnet** [comment] 2019-11-21 10:26
Experience is great, until I looked at the console… I won't register until this simple-to-fix bug is gone.

**Comment by markomarkovic** [comment] 2020-02-04 07:58
This is still an issue with the new command history functionality as shown in the screenshot below. There's already a horizontal scroll in the output section, just the whole dialog needs a hard limit on the width.

![20200204113947-3840x2160](https://user-images.githubusercontent.com/99233/73724775-85b88780-4745-11ea-93a4-fb701517acef.png)

**Comment by willrowe** [comment] 2020-02-04 14:46
I can confirm that this is still an issue because it becomes wider than the viewable screen with no way to view it.

**Comment by DanielPower** [comment] 2020-03-06 19:50
This is also a deal breaker for me. I can't consider using a tool that entirely prevents me from reading console output.

**Comment by willrowe** [comment] 2020-03-30 14:38
I can confirm that this has been fixed in build 2002. It now stays at a smaller width and allows full scrolling.

**Comment by sakekasi** [comment] 2020-03-30 17:15
when will build 2002 make it out to the release?

**Comment by jskinner** [comment] 2020-03-30 20:31
Dev builds are available at https://www.sublimemerge.com/dev

**Closed by jskinner** 2020-03-30 20:31 UTC
