### ISSUE TITLE
Can't discard single, isolated line in Merge's side by side diff view

### ISSUE THREAD

**Issue by facelessuser** [sublimehq/sublime_merge#866] opened 2020-08-14 21:10 UTC
**Version info**

 - OS: macOS Catalina
 - Build: 2028

**Description**

When a single isolated line is modified (and no consecutive lines are modified) and you select just that line and select "Discard Lines", an error occurs.

![merge-bug](https://user-images.githubusercontent.com/1055125/90292706-afaedd00-de3f-11ea-9d17-561e7ed77513.gif)

But if you select multiple lines, the error does not occur. The lines don't even have to be modified.

It also seems that is isn't related to the change only being one line, but maybe how Sublime is detecting whether it *should* discard. If you do a single line discard and it touches a consecutive modified line, it will also have no issue. Even if that second line is itself in compressed diff view.

![merge-okay](https://user-images.githubusercontent.com/1055125/90292847-f4d30f00-de3f-11ea-8998-4a4368366590.gif)

**Steps to reproduce**

1. Open repository
2. Modify a single line
3. Ensure you are in side by side diff view
4. Select the single, modified line
5. Click discard lines
6. Get error

**Expected behavior**

A single, isolated line should properly be discarded.

**Comment by srbs** [comment] 2020-08-14 21:59
@facelessuser is this roughly similar to #865 just on the discard side instead of stage?

**Comment by facelessuser** [comment] 2020-08-14 23:52
Seems like it could be related

**Comment by dpjohnst** [comment] 2020-08-17 00:12
Hi @facelessuser ,

Thanks for reporting this - we're investigating this, and I'll let you know when we have an update.

Thanks,
\- Dylan

**Comment by dpjohnst** [comment] 2020-08-20 03:16
Hi @facelessuser,

We've released Sublime Merge development build 2030. Could you update to this version when you have a chance, and confirm if the issue is resolved.

Thanks,
- Dylan

**Comment by facelessuser** [comment] 2020-08-20 03:24
It does not appear to be fixed. I'm on macOS Catalina, build 2030 of Merge. The case in the first screenshot still fails.

**Comment by facelessuser** [comment] 2020-08-20 03:28
![bug](https://user-images.githubusercontent.com/1055125/90713574-debfb700-e262-11ea-9f23-bd408d9fcd93.gif)

**Comment by dpjohnst** [comment] 2020-08-26 01:35
Hi all,

Thanks to everyone who reported this issue.

A quick update - I've managed to replicate the issue, and there's an upcoming fix for it. Stay tuned.

Kind regards,
\- Dylan

**Comment by srbs** [comment] 2020-09-28 02:13
This should be fixed in the latest development build (2034).

**Comment by facelessuser** [comment] 2020-09-28 02:16
Yes, it is fixed for me.

**Closed** 2020-09-28 08:25 UTC
Labels: bug
