### ISSUE TITLE
Tooltips are unreadable

### ISSUE THREAD

**Issue by scottbilas** [sublimehq/sublime_merge#816] opened 2020-07-07 14:34 UTC
**Version info**

 - OS: Windows 10
 - Build: 2020

**Description**

Tooltips are unreadable. Here are some screen shots:

Push ![image](https://user-images.githubusercontent.com/964720/86796567-04a44a00-c06f-11ea-8d11-fb9c0c69fa21.png)
Stash 
![image](https://user-images.githubusercontent.com/964720/86796634-14239300-c06f-11ea-9569-78cc20686fc6.png)
Back ![image](https://user-images.githubusercontent.com/964720/86796737-30273480-c06f-11ea-82cf-372e44f7db62.png)

Note that status popups look ok. For example:

![image](https://user-images.githubusercontent.com/964720/86796782-3c12f680-c06f-11ea-98d2-a78cd5ecc3c5.png)

I have a couple horizontal 4K monitors stacked on top of each other with DPI set to 150%. The above pics are captured with the app on the lower monitor. If I move it to the upper monitor?

Push ![image](https://user-images.githubusercontent.com/964720/86796985-711f4900-c06f-11ea-9e6a-dc70fbad08c8.png)
Stash ![image](https://user-images.githubusercontent.com/964720/86797026-7bd9de00-c06f-11ea-9640-1fc5b4db1ecb.png)
Back 
![image](https://user-images.githubusercontent.com/964720/86797048-81372880-c06f-11ea-93aa-4c357d34fde3.png)

(Status popups are fine.)

The tooltips are unreadable in either setup, but differently readable depending on which monitor the app is on.

No other apps I use have problems with tooltips or unreadable text.

**Steps to reproduce**

1. Hover over literally anything with a tooltip and it will get a bad rendering.

**Expected behavior**

Readable tooltips.

**Comment by dpjohnst** [comment] 2020-07-07 23:22
Hi @scottlibas,

Could you confirm whether you have hardware acceleration enabled under the preferences?

Additionally, could you confirm the OpenGL Context Information. To find this information, open Sublime Merge, open the console with ctrl + `, and copy the OpenGL Context Information.

Thanks,
\- Dylan

**Comment by scottbilas** [comment] 2020-07-08 14:34
Yes, hw acceleration was enabled. If I disable it and restart, everything is ok. Enabling it again and restarting gives me exactly one good tooltip and after that it's bad again. I also see that Preferences doesn't look so hot too..

![image](https://user-images.githubusercontent.com/964720/86931662-a5ab0780-c138-11ea-9ad2-1b8f3114cb99.png)

```OpenGL Context Information:
  GL API Version: 4.6.13587 Compatibility Profile Context 20.4.2 26.20.15029.27017
  GLSL Version: 4.60
  Vendor: ATI Technologies Inc.
  Renderer: Radeon RX 580 Series```

**Comment by dpjohnst** [comment] 2020-07-09 05:35
Hi @scottbilas,

Thanks for the additional information. It looks as if this is a duplicate of: https://github.com/sublimehq/sublime_merge/issues/782

I'm going to go ahead and close this issue, but please feel free to subscribe to the issue above to continue receiving updates.
The good news is we've identified the driver bug, and will be releasing a work-around soon.

Thanks,
\- Dylan

**Closed by dpjohnst** 2020-07-09 05:35 UTC
Labels: bug
