### ISSUE TITLE
Can't Stage All when too many files modified

### ISSUE THREAD

**Issue by TruePath** [sublimehq/sublime_merge#1233] opened 2021-08-08 03:02 UTC
When there are a huge number of modified files the summary tab is left blank.  It makes sense not to display the changes on that tab when it would be an overwhelming number.  However, a side effect of this is to  also remove the only (at least obvious to me) way to stage all files for a commit.

It would be great to restore the stage all control on the summary tab when many files are changed.

<img width="1381" alt="Screen Shot 2021-08-07 at 10 58 55 PM" src="https://user-images.githubusercontent.com/121223/128619275-3acc06bc-cdc3-4a95-b51c-48ebcde10d60.png">

**Comment by srbs** [comment] 2021-08-08 17:45
Work arounds:

1. Right click the `MODIFIED FILES (1193)` header in the `Files` tab & click `Stage All`
2. Use `Stage All Modified` or `Stage All Modified and Untracked` in the command palette

**Comment by dpjohnst** [comment] 2021-11-22 01:55
Hi @TruePath,

Thank you for sharing this feedback.

As a workaround, please see the tips @srbs shared above (thanks @srbs!)

I'm going to go ahead and close this issue, as it's a duplicate of https://github.com/sublimehq/sublime_merge/issues/710
That being said, we are looking at ways to improve this dialog and will keep you updated on the above issue.

Cheers,
\- Dylan

**Closed by dpjohnst** 2021-11-22 01:55 UTC
Labels: enhancement, ux

**Comment by TruePath** [comment] 2021-11-22 01:58
Ahh, excellent.  That workaround does everything that I need.  Thanks!
