### ISSUE TITLE
Can't verify signature of signed commit GPG

### ISSUE THREAD

**Issue by omBratteng** [sublimehq/sublime_merge#1126] opened 2021-04-29 10:23 UTC
**Version info**

 - OS: macOS 11.3
 - Build: 2052

**Description**

Can't verify signature of signed commit

**Steps to reproduce**

1. Open repository with signed commits
2. View a signed commit
3. Signature shows as red *Invalid*

**Expected behavior**

Signature should show as Valid.
Issue seems to have been introduced in build 2051. Works as expected in 2050 and 2049

**Screenshots**

**Build 2052**
![image](https://user-images.githubusercontent.com/1681525/116536667-7fcc3a80-a8e5-11eb-9f47-0703e530e6cb.png)

**Build 2050**
![image](https://user-images.githubusercontent.com/1681525/116536675-82c72b00-a8e5-11eb-978b-bdf68d7d9dae.png)

**Comment by omBratteng** [comment] 2021-04-29 10:25
Might be related to #1099

**Comment by dpjohnst** [comment] 2021-04-30 05:27
Hi @omBratteng,

Thanks for reporting this issue - I'll be investigating this further.

When you hover over the `Invalid` signature, what output do you see?

Thanks,
\- Dylan

**Comment by omBratteng** [comment] 2021-04-30 07:47
Hi @dpjohnst
**Build 2052**
![image](https://user-images.githubusercontent.com/1681525/116664357-a26b5b80-a998-11eb-8eb4-f052c78c6dca.png)

**Build 2050**
![image](https://user-images.githubusercontent.com/1681525/116664645-0aba3d00-a999-11eb-9dde-917d3f5af30b.png)

**Comment by dpjohnst** [comment] 2021-05-03 09:00
Hi @omBratteng,

Thanks for the additional information!

This issue has been resolved in the latest development version of Sublime Merge (2053).

Kind regards,
\- Dylan

**Comment by omBratteng** [comment] 2021-05-03 09:28
Hi @dpjohnst 
It is now showing up as Valid, although the text seems like the raw gpg output
![image](https://user-images.githubusercontent.com/1681525/116860919-98e52c00-ac02-11eb-97d1-85bc918b3b9d.png)

**Comment by omBratteng** [comment] 2021-05-03 14:02
But at least it is showing as Valid

**Comment by dpjohnst** [comment] 2021-05-05 05:43
Hi @omBratteng,

Thank you for confirming the issue is resolved!

Re. raw gpg output: in order to verify that the commit signature is actually valid, we have to use the command `git verify-commit --raw ID`, and a byproduct of this is that the output is the raw GPG output.

I'm going to go ahead and close this issue as it has been resolved, but feel free to open an enhancement request if you'd like to see any changes to the output and we can definitely investigate.

Thanks,
\- Dylan

**Closed by dpjohnst** 2021-05-05 05:43 UTC
Labels: bug

**Comment by omBratteng** [comment] 2021-05-05 08:06
Hi @dpjohnst, as long as it is the intended output, I am fine with it. Personally I'm more interested in seeing *Valid* or *Invalid*.
