### ISSUE TITLE
Remember the Location Bar Preference when Switching Repos

### ISSUE THREAD

**Issue by tyler8691** [sublimehq/sublime_merge#160] opened 2018-10-22 12:25 UTC
**Problem description**

When opening the Location Bar using the UI or Command + K + B, then switching repos using Command + Shift + O, the bar closes itself. When switching back to the original repo it is still closed.

The bar open/close preference is saved between launches, but not between repos.

**Preferred solution**

Remember the preference globally so users that prefer the Location Bar to always be visible don't have to keep opening it.

**Alternatives**

SM could also remember the preference per-repo if needed.

**Comment by RSeidelsohn** [comment] 2018-10-22 12:52
Duplicate of #158 -  I posted it as a bug, as the state (open or closed) and size of the location bar are stored between sessions since a few versions now, only when switching between repositories, it is reset. So I guess it's not meant to behave differently here than there.

**Closed** 2018-10-22 15:41 UTC
Labels: duplicate
