### ISSUE TITLE
Crash on creating tag

### ISSUE THREAD

**Issue by verside2** [sublimehq/sublime_merge#1647] opened 2022-11-16 11:29 UTC
**Version info**

 - OS: Window 10 Pro (19044)
 - Build: 2078

**Description**

Creating tag crash app.

**Steps to reproduce**

1. Create commit with text "Fix: в случаях, когда у пользователя было всего одно задание, лично присвоенное ему, следующее задание не находилось до момента обновления очереди заданий".
3. Ctrl + Shift + P -> Create Tag.
4. App freeze and crash.

**Expected behavior**

Create tag.

**Screenshots**

![image](https://user-images.githubusercontent.com/12224435/202168852-8c12740c-e4c3-4f3c-acc5-2ded43d9990b.png)

**Comment by dpjohnst** [comment] 2022-11-22 00:03
Hi @verside2,

Thanks for reporting this - we've identified the cause of the issue and it will be fixed in the next build.

Kind regards,
\- Dylan from Sublime HQ

**Comment by dpjohnst** [comment] 2022-12-05 23:54
Hi @verside2,

This has been resolved in Sublime Merge build 2080.

Kind regards,
\- Dylan from Sublime HQ

**Closed by dpjohnst** 2022-12-05 23:54 UTC
