### ISSUE TITLE
Dark mode Files

### ISSUE THREAD

**Issue by ntobolski-r7** [sublimehq/sublime_merge#1402] opened 2022-01-26 18:10 UTC
**Version info**

 - OS: MacOS 11.6.2
 - Build: 2068

**Description**

broken text display in Files tab:
![image](https://user-images.githubusercontent.com/65565003/151221436-a1c1530e-d6bc-4266-9e85-acd4d62843ea.png)

1. Use dark mode
2. View Files tab
3. Observe 

**Expected behavior**

Not broken looking text

**Comment by dpjohnst** [comment] 2022-01-27 05:49
Hi @ntobolski-r7,

Thanks for reporting this issue - this will be resolved in the next build of Sublime Merge.
This is a duplicate of https://github.com/sublimehq/sublime_merge/issues/1363, so I'm going to go ahead and close this issue.
Please feel free to head over to the linked issue to continue to receive updates on the issue.

As a workaround, you can disable OpenGL rendering via the Sublime Merge preferences menu (under the advanced section).

Kind regards,
\- Dylan from Sublime HQ

**Closed by dpjohnst** 2022-01-27 05:49 UTC
