### ISSUE TITLE
Failed to apply patch: No modified lines selected

### ISSUE THREAD

**Issue by safield** [sublimehq/sublime_merge#959] opened 2020-10-23 17:04 UTC
Kubuntu 20.04 , KDE Plasma Desktop 5.18.5
Sublime Merge Stable Channel Build 2032

I am trying to stage some changed lines, and I get the error...

Failed to apply patch: No modified lines selected.

Here are two screenshots, one before the line is selected, and one after the line is selected and the stage lines button has been clicked.

![sublime_merge_error2](https://user-images.githubusercontent.com/12876404/97032738-e718c480-1527-11eb-9c30-a816b5c4cb64.jpg)
![sublime_merge_error1j](https://user-images.githubusercontent.com/12876404/97032743-e849f180-1527-11eb-8b53-feef08faaa4d.jpg)

**Comment by dpjohnst** [comment] 2020-10-25 23:30
Hi @safield,

Thanks for reporting this issue - I have investigate this issue and have found it's a duplicate of https://github.com/sublimehq/sublime_merge/issues/881

The good news is that it has been fixed in the latest development builds of Sublime Merge, and will be available in the next stable build.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment] 2020-11-03 05:34
This was fixed in Sublime Merge Build 2038

**Closed by dpjohnst** 2020-11-03 05:34 UTC
Labels: bug
