### ISSUE TITLE
Text files incorrectly identified as binary

### ISSUE THREAD

**Issue by pmguerre** [sublimehq/sublime_merge#216] opened 2018-11-03 17:23 UTC
**Version info**

 - OS: Windows 10
 - Build: 1084

**Description**

I've tested sublime merge in a scilab's toolbox, and it identified the scilab extensions (*.sci and *.sce), as binary files, but they are text files...

**Steps to reproduce**

1. Open repository git://git.forge.scilab.org/metanet.git
2. View commit db740140cb9888d01665bb0c05fc614a35487c5f, which modified two files: One was the changelog.txt, and the other was macros/graph_tools/show_edges.sci. The first is correctly identified as a text file and it shows the diff, but the second is identified as a binary file, and it just says that the "binary file changed", **but the file is a text file**, not a binary one

**Expected behavior**

Expect the text diff to appear

**Comment by srbs** [comment] 2018-11-05 04:07
Root cause is a file with at least one line using the Mac OS 9 line endings:

    mkdir __test; cd __test
    git init
    printf "file\nwith\nboth\r\nstandard\r\nline\r\nendings\n" > README.md
    git add README.md
    git commit -m working
    printf "file\nwith\nboth\r\nstandard\r\nline\r\nendings\nand\ronly carriage return\n" > README.md
    git commit -am broken
    
    smerge .

**Comment by jskinner** [comment] 2018-11-21 13:01
Thanks for the repros, this has now been fixed in dev build 1088, at https://www.sublimemerge.com/dev

**Closed by jskinner** 2018-11-21 13:01 UTC
