### ISSUE TITLE
open selected version in editor

### ISSUE THREAD

**Issue by br4nnigan** [sublimehq/sublime_merge#890] opened 2020-08-27 15:22 UTC
This is the feature that I miss most from SourceTree

![grafik](https://user-images.githubusercontent.com/10244835/91461646-881d3300-e889-11ea-9eda-0232eeb79e4d.png)

"Open in editor" actually opens the current version (where head is) in editor, not the version of the selected commit we're looking at.

A second option "open _selected version_ in editor" would be the bomb.

**Comment by srbs** [comment] 2020-08-27 18:38
duplicate of #49 

workaround: blame & copy+paste (or potentially, show entire fire & copy+paste)

**Comment by dpjohnst** [comment] 2020-08-28 02:24
Hi @br4nnigan,

Thank you for sharing this request. 

As @srbs mentioned this is a duplicate of #49. I'm going to go ahead and close this issue, but I'd suggest heading over to the linked issue and subscribing to it to continue to receive updates.

Thanks,
\- Dylan

**Closed by dpjohnst** 2020-08-28 02:24 UTC
