### ISSUE TITLE
Search Commit/Working Directory

### ISSUE THREAD

**Issue by safield** [sublimehq/sublime_merge#387] opened 2019-02-15 20:22 UTC
It would be nice to have  a search box to search for files in the current commit/working directory of the currently displayed commit in the contents view.

Right now, if I have a bunch of changed files, and I want to see the changes for a specific file, there is no way for me to quickly find that specific changed file, without just manually/visually parsing through the list.

**Comment by srbs** [comment] 2019-02-15 22:17
Duplicate of #330.

**Comment by wbond** [comment] 2019-03-08 18:01
Closing as a duplicate

**Closed by wbond** 2019-03-08 18:02 UTC
