### ISSUE TITLE
Some tags aren't selectable from the sublime merge UI

### ISSUE THREAD

**Issue by tkuraku** [sublimehq/sublime_merge#804] opened 2020-06-18 00:03 UTC
**Version info**

 - OS: Windows 10
 - Build: 2022

**Description**
Some tags aren't loaded from opencv. I freshly cloned the opencv repository from https://github.com/opencv/opencv.git. the tags labeled X.X.X-openvino aren't navigated to when I select them in the locations sidebar. If I manually checkout one of those tags from the command line and then select it in the sublime merge UI it works.

**Steps to reproduce**

1. clone opencv https://github.com/opencv/opencv.git
2. In the tags section of the Locations bar select 4.3.0 to navigate to that tag
3. In the tags section of the Locations bar select 4.3.0-openvino and the UI doesn't do anything.
4. On the command line "git checkout 4.3.0-openvino" and it works as expected and then the sublime UI correctly navigates to that tag. 

**Expected behavior**

navigate to the -openvino tags like the other tags.

This seems like a bug with tag names and sublime merge.

**Comment by srbs** [comment] 2020-06-18 09:38
Duplicate of #176

Your root cause is those tags point to commits which don't exist within any branch:

<img width="685" alt="Screen Shot 2020-06-18 at 04 38 14" src="https://user-images.githubusercontent.com/297298/85004800-99292580-b11d-11ea-93ce-398b18cc40ba.png">

**Closed** 2020-06-18 14:38 UTC
