### ISSUE TITLE
Latest installer on Windows

### ISSUE THREAD

**Issue by VipSaran** [sublimehq/sublime_merge#843] opened 2020-07-28 07:34 UTC
press install and the installer breaks:
![image](https://user-images.githubusercontent.com/995948/88633611-8824ea00-d0b5-11ea-8a1e-d894d55a94e0.png)

**Comment by stinos** [comment] 2020-07-28 07:36
That's not the installer which breaks, it's Sublime Merge which crashes when closing (see dialog text). Just click 'Close program' and installation continues.

**Comment by VipSaran** [comment] 2020-07-28 09:43
Well, for the user it's the same difference --> something unexpected has happened and it involved Sublime Merge install operation.

**Comment by dpjohnst** [comment] 2020-07-29 01:36
Hi @VipSaran,

Thanks for reporting this - I believe this is a duplicate of #842 as @stinos mentioned.
I'm going to go ahead and close this issue, but please feel free to follow along on #842.

That being said, the issue has been identified and will be fixed in the next build of Sublime Merge.

Kind regards,
\- Dylan

**Closed** 2020-07-29 01:36 UTC
