### ISSUE TITLE
use of onion skin crashes on second use consistently

### ISSUE THREAD

**Issue by cppforlife** [sublimehq/sublime_merge#1191] opened 2021-06-28 12:50 UTC
**Version info**

 - OS: macOS 10.15
 - Build: 2056

**Description**

Comparing png via "onion skin" method results in a crash (sublime merge quits) on the second time.

**Steps to reproduce**

go to 1st png image, move the onion skin slider to the new version, all ok so far, go to 2nd png image, move the onion skin slider to the new version -> crash. happens consistently.

**Expected behavior**

Not crash.

**Comment by srbs** [comment] 2021-06-29 01:23
It took me a while to reproduce crashes using onion skin. For me, I could not (in any way) reproduce using the onion skin in the entire-commit diff. However, here is an additional case & more details:

case 1:
1. change `Default Image Diff Style` to `Onion skin` & restart SM
2. navigate to commit with at least one image change
3. open Files side bar
4. select image
5. drag slider
6. notice immediate crash
    * happens both with hardware acceleration turned on and off

case 2: (ticket original)
1. change `Default Image Diff Style` to `Side by side` & restart SM
2. navigate to commit with at least two images changed
3. open Files side bar
4. select an image
5. drag slider
6. select another image
7. drag slider
8. notice immediate crash
    * happens both with hardware acceleration turned on and off

I'm on macOS 10.14 & build 2055.

**Comment by dpjohnst** [comment] 2021-06-30 00:20
Hi all,

Thanks a lot for reporting this - this should be resolved in Sublime Merge Build 2057 (development build).

@srbs could you confirm these are resolved for you?
@cppforlife this will be fixed in the next stable build - once released, could you confirm the issue is resolved on your end?

Cheers,
\- Dylan

**Comment by srbs** [comment] 2021-06-30 06:00
@dpjohnst, everything is working well for me, thanks!

**Comment by dpjohnst** [comment] 2021-07-28 01:56
Hi all,

This was fixed in Sublime Merge Build 2057 (Dev) / 2059 (Stable)!

Cheers,
\- Dylan from Sublime HQ

**Closed by dpjohnst** 2021-07-28 01:56 UTC
Labels: bug
