### ISSUE TITLE
Commit message doesn't allow messages with hashtag anymore

### ISSUE THREAD

**Issue by elvishribeiro** [sublimehq/sublime_merge#1340] opened 2021-11-29 15:03 UTC
**Version info**

 - OS: Windows 10
 - Build: 2063

**Description**
In the latest update, Sublime Merge won't accept commit messages which contains hashtag (#) character. It just pops out the following message: "error: switch `m' requires a value"

**Steps to reproduce**
- Stash some files
- Try to commit a message with hashtag symbol, e.g: "#112345 - Fixes general bugs"
- Click on commit button

**Expected behavior**
Should pop the tooltip containing the message "error: switch `m' requires a value", and the commit is not done.

**Screenshots**
![image](https://user-images.githubusercontent.com/43489254/143891520-c3dd6d33-adcc-441d-b1b6-b232c1e997d9.png)

**Comment by srbs** [comment] 2021-11-29 19:01
duplicate of #1307

**Closed** 2022-09-07 20:48 UTC
