### ISSUE TITLE
Phantom staging files won't go away

### ISSUE THREAD

**Issue by fosterbrereton** [sublimehq/sublime_merge#913] opened 2020-09-15 04:23 UTC
**Version info**

 - OS: macOS 10.15.4
 - Build: 2032
- `git` version `2.28.0` (installed via Homebrew)

**Description**

My repo is plagued with files that are always staged. See attached screenshot.

I'm uncertain how the repo got into the state it's in. From iTerm, when I run `git status` over the same repository, these files do not show. Unstaging the files within Sublime Merge makes them go away, however they return after a subsequent run of `git status` from the command line.

I am able to temporarily make them go away by clearing the index of the repository. I go this by deleting `.git/index`, running `git reset`, then `git status`. The phantom files return, however, once I change branches.

**Steps to reproduce**

Unfortunately I do not know how I got the repository in the state it is in. The problems started when I installed [Microsoft Scalar](https://devblogs.microsoft.com/devops/introducing-scalar/) on my machine, but have since removed it. I'm still finding vestiges of it in my system and am slowly cleaning it out. (The Debug Information supplied does mention it (and watchman, the tool it uses) in the config section. I've tried clearing those since the Debug Information was gathered, but it didn't change anything.

**Expected behavior**

Sublime Merge should show the same staging status as `git status` when run from the command line.

**Screenshots**

<img width="925" alt="Screen Shot 2020-09-14 at 8 58 22 p" src="https://user-images.githubusercontent.com/1664117/93163940-3c61ea80-f6cd-11ea-86f2-dec7699f0ce2.png">

**Debug Information**

```=== App Version Information ===
Build: 2032

=== Git Version Information ===
Using Git: git (system)
git version 2.28.0
PATH: /usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:~/.pyenv/shims:~/.pyenv/bin:~/.cargo/bin:~/.rbenv/shims:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:~/Library/Android/sdk/tools:~/Library/Android/sdk/tools/bin:~/Library/Android/sdk/tools/bin/sdkmanager:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/ndk/21.1.6352462 (from shell)
environment variables loaded using: /bin/bash -l

=== Browse Page Information ===
HEAD: 9bc5ba476a99fd6827ff6aa920119ba4a8486e46
Is in merge: 0
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===

=== Our Status Information ===
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/m_xxx.md
A  docs/xxxxxxxx/m_xxx.md
A  docs/xxxxxxxx/m_xxx.md
A  docs/xxxxxxxx/m_xxx.md
A  docs/xxxxxxxx/m_xxx.md
A  docs/xxxxxxxx/m_xxx.md
A  docs/xxxxxxxx/m_xxx.md
A  docs/xxxxxxxx/m_xxx.md
A  docs/xxxxxxxx/m_xxx.md
A  docs/xxxxxxxx/m_xxx.md
A  docs/xxxxxxxx/m_xxx.md
A  docs/xxxxxxxx/m_xxx.md
A  docs/xxxxxxxx/m_xxx.md
A  docs/xxxxxxxx/m_~brush.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/xxx.md
A  docs/xxxxxxxx/f_xxx_string.md
A  docs/xxxxxxxx/f_operator213D.md
A  docs/xxxxxxxx/f_operator3D3D.md
A  docs/xxxxxxxx/index.md
A  docs/xxxxxxxx/index.md
A  docs/xxxxxxxx/m_as_tuple.md
A  docs/xxxxxxxx/m_operator3D.md
A  docs/xxxxxxxx/m_tool_state.md
A  docs/xxxxxxxx/m_~tool_state.md

=== Git Config Information ===
alias.br=xxx
alias.ci=xxx
alias.co=xxx
alias.current-branch=xxx
alias.discard=xxx
alias.l=xxx
alias.last=xxx
alias.lol=xxx
alias.lola=xxx
alias.main=xxx
alias.mkbr=xxx
alias.note=xxx
alias.st=xxx
alias.subup=xxx
alias.unadd=xxx
alias.unstage=xxx
alias.visual=xxx
am.keepcr=xxx
=== 12 branch lines redacted ===
color.branch=auto
color.diff=auto
color.interactive=auto
color.stats=true
color.status=auto
color.ui=true
commit.template=~/.stCommitMsg
core.autocrlf=false
core.bare=false
core.editor='subl' --wait
core.excludesfile=~/.gitignore_global
core.filemode=true
core.fscache=true
core.fsmonitor=/some/path/to/.git/hooks/query-watchman
core.fsmonitorhookversion=2
core.hookspath=/some/path/to/.git/hooks
core.ignorecase=true
core.logallrefupdates=true
core.multipackindex=true
core.precomposeunicode=true
core.preloadindex=true
core.repositoryformatversion=0
core.safecrlf=false
core.untrackedcache=true
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
credential.validate=false
diff.tool=smerge
difftool.sourcetree.cmd=/some/path/to/diff -2 "$LOCAL" "$REMOTE"
difftool.sourcetree.path=
feature.experimental=false
feature.manyfiles=false
fetch.unpacklimit=1
fetch.writecommitgraph=false
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.smudge=git-lfs smudge -- %f
filter.media.clean=git media clean %f
filter.media.required=true
filter.media.smudge=git media smudge %f
gc.auto=0
gui.gcwarning=false
index.threads=true
index.version=4
log.excludedecoration=refs/scalar/*
merge.renames=false
merge.stat=false
merge.tool=smerge
mergetool.smerge.cmd=smerge mergetool "$BASE" "$LOCAL" "$REMOTE" -o "$MERGED"
mergetool.smerge.trustexitcode=true
mergetool.sourcetree.cmd=/some/path/to/diff "$REMOTE" "$BASE" "$LOCAL" "$MERGED"
mergetool.sourcetree.trustexitcode=true
pack.usebitmaps=false
pack.usesparse=true
pull.rebase=false
push.default=simple
receive.autogc=false
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=git@git.xyz.com:xxxxxxxx/xxxxxxxx.git
reset.quiet=true
status.aheadbehind=false
=== 140+ submodule lines redacted ===
user.email=xxxxxxxx
user.name=xxxxxxxxx

=== Our Config Information ===
Git Config Path Information
Using config path: /etc/gitconfig
Using config path: ~/.config/git/config
Using config path: ~/.gitconfig
Using config path: /some/path/to/.git/config

Our config output is identical to the Git config output

=== Git Attributes Information ===
git check_attr --all output

=== Our Modified Files Newline Normalisation and EOL Information ===

=== Our Modified Files Flag Information ===
Ignoring symlinks: 0
```

**Comment by dpjohnst** [comment] 2020-09-15 06:56
Hi @fosterbrereton,

Thanks for reporting this issue.

This is an odd one indeed. I have a suspicion that this is a case of autocrlf config settings + a strange index.
After reading about Scalar, I'm suspicious of the fact that they change multiple Git config values and also install a custom version of Git.

Could you confirm the following:
* Run `git -- version` from the command line and confirm the output
* Confirm whether the repository contains any files with CRLF line endings (this can be the case if you develop on Windows). If you're unsure, just let me know whether any Windows users commit to the repository.

Thanks,
\- Dylan

**Comment by fosterbrereton** [comment] 2020-09-15 07:15
Hi @dpjohnst -

- I can confirm that `git --version` from the command line returns `git version 2.28.0`.
- While we have lots of Windows developers across the team, I cannot speak to the line endings of sources or other files. Our repo is 100,000s of files in size, so invariably there are some with CRLF line endings.

**Comment by dpjohnst** [comment] 2020-09-15 07:44
Hi @fosterbrereton,

Thanks for the additional information.

Could you confirm whether setting `autocrlf` to `input` fixes the issue. To do so, perform the following steps:
1. Open terminal
2. Navigate to the repository, and run the command `git config --local core.autocrlf input`
3. Re-check out the current branch (check out another branch, then check out the initial branch).

Thanks,
\- Dylan

**Comment by fosterbrereton** [comment] 2020-09-15 16:31
Hi @dpjohnst,

I changed the setting, then confirmed it is `input`. After moving between branches, the ghost files are still there 👻 

Thanks for your help,
Foster

**Comment by dpjohnst** [comment] 2020-09-16 23:41
Hi @fosterbrereton,

Thanks for sharing this. So far I haven't had luck replicating the issue, but rest assured we'll get to the bottom of this.

Could you confirm the following:
* Whether you have a .gitattributes file (and if so, whether you could share the contents of it)
* Could you confirm the line endings on one of the staged files in question. One way to do this would be to open the file in Sublime Text and navigate to `view > line endings`, and check which line endings are selected.
* Could you navigate to the repository via console, and run `stat PATH_TO_FILE` for any one of the files marked as staged, and share the output

Thanks,
\- Dylan

**Comment by fosterbrereton** [comment] 2020-09-16 23:48
Hi @dpjohnst, thanks for keeping on top of this one. Here are the answers you seek:

- There is no top-level `.gitattributes` file in the repo
- The line endings are Unix:
<img width="389" alt="Screen Shot 2020-09-16 at 4 44 17 p" src="https://user-images.githubusercontent.com/1664117/93403355-2292e580-f83c-11ea-9620-85d80b0ac31b.png">

- The (lightly modified) stat results are as follows:
```
stat /path/to/brush.cpp
16777227 38372236 -rw-r--r-- 1 username staff 0 28882 "Sep 16 16:43:53 2020" "Sep 16 15:41:43 2020" "Sep 16 15:41:43 2020" "Sep 16 11:54:24 2020" 4096 64 0x40 /path/to/brush.cpp
```

**Comment by dpjohnst** [comment] 2020-09-17 01:25
Hi @fosterbrereton,

Thanks for your patience while I investigate this - one more request if you have the time:
Could you run `stat -x PATH_TO_FILE` and share the contents (feel free to omit any sensitive info).

Thanks,
\- Dylan

**Comment by fosterbrereton** [comment] 2020-09-17 16:42
Here's what comes back:
```shell
stat -x path/to/file.md
  File: "path/to/file.md"
  Size: 1412         FileType: Regular File
  Mode: (0644/-rw-r--r--)         Uid: (  501/username)  Gid: (   20/   staff)
Device: 1,11   Inode: 33238971    Links: 1
Access: Wed Sep 16 11:17:37 2020
Modify: Mon Sep 14 19:46:04 2020
Change: Mon Sep 14 19:46:04 2020
```

**Comment by dpjohnst** [comment] 2020-09-17 18:54
Hi @fosterbrereton,

Thank you for the additional information. This has all helped a lot to narrow down on the issue. 

Could you confirm whether the staged files contain any diff contents?

I suspect the diff will show all lines changed from LF (Unix) line endings to CRLF (Windows) line endings and no other changes. Could you confirm this is the case?

Kind regards,
\- Dylan

**Comment by fosterbrereton** [comment] 2020-09-17 20:14
> Could you confirm whether the staged files contain any diff contents?

There are no diff contents in these files - they appear in Sublime Merge as if the whole file is new (the entire body of the file has a green background.)

> I suspect the diff will show all lines changed from LF (Unix) line endings to CRLF (Windows) line endings and no other changes. Could you confirm this is the case?

How would I do such a diff? `git diff` from my command line doesn't show any of these staged files. If I try to unstage one of these ghost files in Sublime Merge and then do a CLI `git diff`, the ghost file is re-staged and the diff command returns nothing.

**Comment by dpjohnst** [comment] 2020-09-18 00:10
Hi @fosterbrereton,

Great news, I've managed to replicate the issue and will be investigating this further.
I'll keep you updated as the investigation progresses.

Thanks again for your assistance in investigating this.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment] 2020-09-18 02:11
Hi @fosterbrereton,

I've located the cause of the issue - this will be fixed in an upcoming build of Sublime Merge.

Thanks,
\- Dylan

**Comment by fosterbrereton** [comment] 2020-09-18 02:20
Brilliant - thank you!!

**Comment by dpjohnst** [comment] 2020-09-25 09:04
Hi @fosterbrereton,

Just a quick update - this has been resolved in the latest development build (2034) and will be available in the next stable build.

Kind regards,
\- Dylan

**Comment by fosterbrereton** [comment] 2020-09-25 17:22
You are a champion. Thank you for your persistence in hunting this one down!

**Closed** 2020-09-29 01:11 UTC
Labels: bug, config

**Comment by joelekstrom** [comment] 2022-06-08 07:24
Hi @dpjohnst I can unfortunately report that I now have this issue in version 2073, dev channel. about 50 files show as staged while `git status` shows clean repo. Seems impossible to get rid of them

**Comment by dpjohnst** [comment] 2022-06-08 07:36
Hi @joelekstrom,

Thanks for reporting this issue - I can investigate this further.

When you have a spare moment, could you open a new issue on the issue tracker and include the following information:
* OS and Version
* Sublime Merge Build Number
* Sublime Merge Debug Information
    * This can be found in Sublime Merge via `Help > Debug Information`
    * Before sharing this information, take a moment to redact any information that is sensitive such as Git user information, remotes, file paths etc

Cheers,
\- Dylan from Sublime HQ

**Comment by ygabo** [comment] 2023-12-06 03:22
Is this fixed? How do we get the staged files to go away?

**Comment by harkairt** [comment] 2024-08-02 08:31
I have the same issue. (I do not know why, I've been using sm on this repository for almost 2 years)

**Comment by zghorn** [comment] 2024-12-05 17:29
It's happening to me every couple months, too!

**Comment by chbi-vcas** [comment] 2025-11-28 11:01
I had the exact same issue. Running `git gc` in the terminal solved it for me.

**Comment by dpjohnst** [comment] 2025-12-03 05:08
G'day all,

We've just released Sublime Merge Build 2117, which should resolve an issue where certain packfiles generated by Git Maintenance weren't being loaded. This will likely resolve the above issue for some of you.

After upgrading to 2117, if you're still seeing this issue please open a new issue report on the issue tracker and we'll investigate further.

Kind regards,
Dylan from Sublime HQ
