### ISSUE TITLE
Submodule commit hash not updated on initialization

### ISSUE THREAD

**Issue by Jelb** [sublimehq/sublime_merge#1653] opened 2022-11-21 12:47 UTC
**Version info**

 - OS: Windows 10
 - Build: 2079

**Description**

Submodule commit hash is left as "0000..." in location bar after initialization of submodule. Information is not updated until Sublime Merge is restarted.

**Steps to reproduce**

1. Clone repository with one or more submodules
2. Initialize submodule

**Expected behavior**

After initializing the submodule the commit hash in the location bar should be updated to match the commit that is checked out in the submodule.

**Screenshots**
Submodule after clone of repo.
![SublimeMerge_pre_initialize](https://user-images.githubusercontent.com/3618069/203058057-1dc9cd03-70a6-407e-8243-efac196b09c8.png)

Result of initialize command.
![SublimeMerge_initialize](https://user-images.githubusercontent.com/3618069/203058088-e5d398e3-7145-4c43-bdc1-0c8a87aa4f7b.png)

Submodule after initialize command.
![SublimeMerge_post_initialize](https://user-images.githubusercontent.com/3618069/203058164-c28ac423-9c78-4d5f-8430-527f9e591b6f.png)

Submodule after reboot of Sublime Merge.
![SublimeMerge_post_reboot](https://user-images.githubusercontent.com/3618069/203058720-70b05053-9abc-48b7-bee3-3317ec769215.png)

**Comment by dpjohnst** [comment] 2022-11-23 04:01
Hi @Jelb,

Thanks for reporting this issue - we've identified the cause of the issue and a fix will be added to the next build.

Kind regards,
\- Dylan from Sublime HQ

**Comment by dpjohnst** [comment] 2022-12-06 00:00
Hi @Jelb,

Just a quick update that this has been resolved in Sublime Merge build 2080 (development build) and will be available in the next stable build.

Kind regards,
\- Dylan from Sublime HQ

**Closed by dpjohnst** 2022-12-06 00:00 UTC
