### ISSUE TITLE
Failed to push refs when git-lfs is required (again)

### ISSUE THREAD

**Issue by aeisenberg** [sublimehq/sublime_merge#1473] opened 2022-04-25 20:12 UTC
I just upgraded to build 2071 and I am hitting this error again: https://github.com/sublimehq/sublime_merge/issues/1138

I haven't made any other changes to my system other than upgrading. Pushing from the CLI works with no problems. 

The debug info includes: 

```
=== Git Version Information ===
Using Git: git (system)
git version 2.32.0 (Apple Git-132)
PATH: /usr/bin:/bin:/usr/sbin:/sbin
no output from shell "/usr/local/bin/bash" in 1500ms
```

In the terminal:

```
$ git version
git version 2.33.0
$ which git
/usr/local/bin/git
$ which git-lfs
/usr/local/bin/git-lfs
```

I have tried changing the git binary path to "bundled" as well as `/usr/local/bin/git`. None of these are working.

**Version info**

 - OS: MacOS 12.3.1 (21E258)
 - Build: 2071

**Description**

I try to push a repository that requires git-lfs and I get the following error:

```
his repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.

error: failed to push some refs to 'github.com:xxx/xxx.git'
```

**Steps to reproduce**

See  https://github.com/sublimehq/sublime_merge/issues/1138

**Expected behavior**

See  https://github.com/sublimehq/sublime_merge/issues/1138

**Comment by dpjohnst** [comment] 2022-04-26 01:05
Hi @aeisenberg,

Thanks for reaching out!

Based on the debug information above, it looks as if the `PATH` variable is failing to load. See:
```
no output from shell "/usr/local/bin/bash" in 1500ms
```

This indicates that when Sublime Merge tries to start `bash` to capture the PATH variable, it's timing out after 1.5 seconds.
This can be caused by long running tasks within the login profile (`.bash_profile`), causing a timeout. If this is the case, you can move these tasks into the interactive profile (`.bashrc`).

Could you confirm if this is the case on your end? If not, I'll investigate further.

Kind regards,
\- Dylan

**Comment by aeisenberg** [comment] 2022-04-26 02:13
Thanks, Dylan. That was exactly the problem. My bashrc is slow to load. Interesting that it is a problem in this version, but not in previous versions.

**Comment by dpjohnst** [comment] 2022-05-04 01:08
Hi @aeisenberg,

Glad it could be resolved! I'm going to go ahead and close this issue now but please reach out if the problem persists.

Kind regards,
- Dylan

**Closed by dpjohnst** 2022-05-04 01:08 UTC
