### ISSUE TITLE
Persistent window size/position

### ISSUE THREAD

**Issue by mz-111** [sublimehq/sublime_merge#910] opened 2020-09-12 18:31 UTC
Each time I open Sublime Merge, the window is quite small and in an inconvenient place for me on the screen, so the first thing I have to do is to resize and move it. It would be great if the window would get created in the same size and position that it had the last time I closed it. Alternatively, allowing some sort of configuration for where the window should get created and in what size would solve the issue as well. (I am opening Sublime Merge from the Sublime Text side bar's context menu, if it matters.)

**Comment by dpjohnst** [comment] 2020-09-15 00:25
Hi @mz-111,

Thanks for reporting this issue. 

This is most likely a duplicate of https://github.com/sublimehq/sublime_merge/issues/396.
I'm going to close this issue, but I definitely encourage you to subscribe (or comment on) the issue linked above to continue to receive status updates.

Thanks,
\- Dylan

**Closed by dpjohnst** 2020-09-15 00:25 UTC

**Comment by mz-111** [comment] 2020-09-15 07:46
Great, thanks.
–Martin
