### ISSUE TITLE
UI is off by few cm from top

### ISSUE THREAD

**Issue by vincent-blyat** [sublimehq/sublime_merge#1085] opened 2021-03-10 05:27 UTC
**Version info**
 - OS:  Windows 10
 - Build: 2047

**Description**

UI is off by a few cm from the top. It works when I hit F11. But when I use it in a normal window or minimized. I have to point my pointer a little bit to the top to click a button.

**Steps to reproduce**

Open the app.

**Expected behavior**

UI must be in place

**Screenshots**
Notice that there is a black section that is pushing UI down
If applicable, add screenshots to help explain your problem. This section may be omitted/removed.
![image](https://user-images.githubusercontent.com/29142786/110580495-c766fd80-81a3-11eb-8266-c054b0f900b2.png)
![image](https://user-images.githubusercontent.com/29142786/110580563-e9f91680-81a3-11eb-9a23-66953ea82124.png)
![image](https://user-images.githubusercontent.com/29142786/110580622-01d09a80-81a4-11eb-997c-833a43bfb9d3.png)
![image](https://user-images.githubusercontent.com/29142786/110580779-4b20ea00-81a4-11eb-92d7-9f7478d7415d.png)

**Comment by dpjohnst** [comment] 2021-03-10 05:36
Hi @vincent-blyat,

Thanks for reporting this issue - unfortunately this is a bug with some Intel GPU drivers.
See https://github.com/sublimehq/sublime_merge/issues/1068 for more information and work-arounds.

I'll go ahead and close this issue, as it's a duplicate of the above.

Kind regards,
\- Dylan

**Closed** 2021-03-10 05:37 UTC
