### ISSUE TITLE
Default Stage/Unstage listed shortcut appears to be incorrect

### ISSUE THREAD

**Issue by adamscoble** [sublimehq/sublime_merge#1165] opened 2021-06-01 00:35 UTC
**Version info**

 - OS: Windows
 - Build: 2056

**Description**

The shortcut to Stage/Unstage files is listed as Shift+Enter, however pressing this does nothing. Pressing just Enter Stages/Unstages the files correctly.

**Steps to reproduce**

Hover over a file in either the Unstaged or Staged sections to see the default shorter to Stage/Unstage listed as Shift+Enter.
Click a file in either the Unstaged or Staged sections and press Shift+Enter, nothing will happen. (Pressing Enter will perform the action.)

**Comment by dpjohnst** [comment] 2021-06-17 06:48
Thanks for reporting this @adamscoble!

I'm going to close this as it's a duplicate of https://github.com/sublimehq/sublime_merge/issues/778, but feel free to follow along there.

Cheers,
\- Dylan

**Closed by dpjohnst** 2021-06-17 06:48 UTC
