### ISSUE TITLE
Allow for opening URLs from the git push output

### ISSUE THREAD

**Issue by schultzor** [sublimehq/sublime_merge#693] opened 2020-03-11 20:37 UTC
**Problem description**

After pushing to a branch on a remote repo, GitHub/GitLab will often send back a URL that can be used to open a Pull Request for the change. It'd be handy if you could click on that link right from Sublime Merge, right now I have to copy it and paste it into a browser manually.

**Preferred solution**

Highlight URLs in the git command output sheet and allow them to be clicked to open them in your browser.
<img width="1182" alt="Screen Shot 2020-03-11 at 3 30 34 PM" src="https://user-images.githubusercontent.com/3588613/76461605-33a2fb80-63ae-11ea-9799-e9bab563d4db.png">

**Alternatives**

**Screenshots**=

**Comment by dpjohnst** [comment] 2020-03-11 23:40
Hi @schultzor,

Thanks for the suggestion! This is definitely something we'd be interested in adding. We will be investigating ways we can add this functionality in the future.

Kind regards,
\- Dylan

**Comment by srbs** [comment] 2020-03-17 19:21
Duplicate of #42

**Closed** 2020-03-30 05:17 UTC
Labels: duplicate, enhancement
