### ISSUE TITLE
ssh-askpass enhancement

### ISSUE THREAD

**Issue by ratijas** [sublimehq/sublime_merge#1011] opened 2020-12-11 12:10 UTC
**Problem description**

Ssh-Askpass-Sublime is an **ssh**(1) helper bundled with Sublime Merge. It's implementation is (quoting) "quite basic", which leads to funny situations like on a screenshot one below.

**Preferred solution**

ssh-askpass agent should recognize common scenarios, such as establishing authenticity of host and verifying its key fingerprint. It should not present a password field in this case, but instead provide UI with appropriate buttons (Yes/No) and a text field for user to paste a fingerprint.

Ideally, it should figure out if the clipboard's content "looks like" a fingerprint and automatically paste it in -- just like a clone repo URL field in SM empty tab. Then, the fingerprints would be compared, and if there is a mismatch — text field lights up with red border/background and the 'Yes' button deactivates.

**Alternatives**

Full blows terminal would be an overkill.

**Screenshots**

![Are you sure you want to continue connecting](https://media.discordapp.net/attachments/492382584588992523/786783740444672050/Screenshot_20201211_053645.png)

> The authenticity of host 'aur.archlinux.org (95.216.144.15)' can't be established.
> ECDSA key fingerprint is SHA256:uTa/0PndEgPZTf76e1DFqXKJEXKsn7m9ivhLQtzGOCI.
> Are you sure you want to continue connecting (yes/no/[fingerprint])? 
> [ Password textfield which hides letters with dots ]
> [Cancel] [OK]

**Comment by dpjohnst** [comment] 2020-12-16 02:41
Hi @ratijas,

Thanks for reporting this issue.

Looking into this further, it looks like we already have basic support for yes/no input, but we weren't detecting this case correctly.
I've produced a fix for this, and it should be available in the next build.

Cheers,
\- Dylan

**Comment by Taknok** [comment] 2021-01-12 08:35
ssh-askpass is also displayed with wrong text when trusting server for 1st time at 1st cloning (at least on windows):

Steps to reproduce with a fresh install:
1. Install sublime merge
2. Generate an ssh ed25519
3. Add ssh.exe to path
4. Restart sublime merge
5. Add the key.pub to your favorite website
6. Clone ssh repo with sublime merge
7. Sublime merge ask for key passphrase indefinitely.
8. Type "yes" as "_Are you sure you want to continue connecting ? (yes/no)_"
9. It is working

**Comment by dpjohnst** [comment] 2021-01-29 05:22
Thanks for the feedback - this should be fixed in the latest development build

**Comment by dpjohnst** [comment] 2021-02-23 22:40
Hi all,

Just following up that this was released to the stable channel (Sublime Merge Build 2047)

Cheers,
\- Dylan

**Closed by dpjohnst** 2021-02-23 22:40 UTC
Labels: bug, ux
