### ISSUE TITLE
Recent update prevents sublime from starting

### ISSUE THREAD

**Issue by mibzman** [sublimehq/sublime_merge#475] opened 2019-04-25 17:12 UTC
### Description

After the most recent update, sublime merge will not open.  when you click on it, it attempts to open and then immediately closes. This is nearly the same behavior as https://github.com/SublimeTextIssues/Core/issues/2791, except I can't find the sublime merge settings file. 

### Steps to reproduce

1. Open Sublime Merge

### Expected behavior

Sublime opens

### Actual behavior

Sublime Doesn't open

### Environment

* I don't know, I can't open Merge.  Sublime Text is 3.2.1, Build 3207
* Operating system and version: macOS 10.14

**Comment by mibzman** [comment] 2019-04-25 17:18
I just tried to re-download Build 1107 from the website and the same behavior occurs.

**Comment by srbs** [comment] 2019-04-26 00:08
Location for the preferences file: `~/Library/Application Support/Sublime Merge/Packages/User/Preferences.sublime-settings`. You may have to create it if it doesn't exist.

**Comment by mibzman** [comment] 2019-04-26 12:48
I created a preference file at that locaion, and added:
```
{
	"gpu_window_buffer": false
}
```

and now merge opens!  Thank you!

**Comment by jskinner** [comment] 2019-05-24 05:00
This was caused by an OpenGL issue in macOS 10.14.4, which has been fixed in 10.14.5

**Closed by jskinner** 2019-05-24 05:00 UTC
