### ISSUE TITLE
Invalid input field

### ISSUE THREAD

**Issue by masj56** [sublimehq/sublime_merge#1431] opened 2022-03-04 03:11 UTC
I open sublime merge, first open a git repository, then I click File → Open Recent → Select, there is a list showing my recently opened repositories, and then when I want to enter a word in the input field on this list to search, The input field cannot input anything, neither the Chinese input method nor the default ABC input method. I can only click New Tab and repeat this operation, this should be a bug.

Build 2068
macos 12.2.1

**Comment by dpjohnst** [comment] 2022-03-11 04:33
Hi @masj56,

Thanks for reporting this issue - this is a duplicate of https://github.com/sublimehq/sublime_merge/issues/1319
I'm going to close this issue, but please feel free to move to the linked issue above where I will keep you updated on progress.

Kind regards,
\- Dylan from Sublime HQ

**Closed by dpjohnst** 2022-03-11 04:33 UTC
