### ISSUE TITLE
The suggested key shortcut from the context menu does not work

### ISSUE THREAD

**Issue by boaz001** [sublimehq/sublime_merge#870] opened 2020-08-18 06:46 UTC
**Version info**

 - OS: Windows 10
 - Build: 2027

**Description**

The suggested shortcut for staging or discarding a file is Shift+Enter or Shift+Backspace, but those do not work. Note that without Shift (so just Enter or Backspace) it does work.
![merge](https://user-images.githubusercontent.com/3184497/90479686-5987b580-e12f-11ea-98cc-0432658e2041.png)

**Steps to reproduce**

1. Open repository
2. Go to the files tab
3. Select a modified file
4. Press Shift+Backspace

**Expected behavior**

The file to be discarded.

**Comment by Gabriel-p** [comment] 2020-10-03 23:51
Can confirm that this also happens in Linux (elementary OS 5.1.7 Hera, based on Ubuntu 18.04.4 LTS)

**Comment by dpjohnst** [comment] 2021-06-17 06:47
Thanks for reporting this!

Closing as this is a duplicate of https://github.com/sublimehq/sublime_merge/issues/778, but feel free to follow along there.

**Closed by dpjohnst** 2021-06-17 06:47 UTC
Labels: S: trivial, bug
