### ISSUE TITLE
Caret disappears in commit message edit control after backspace

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#893] opened 2020-08-28 20:09 UTC
**Version info**

 - OS: Windows 10 2004
 - Build: 2031

**Description**

When editing the commit message of an existing (and maybe new?) commit, the caret disappears after deleting something via backspace key, if it is then moved after the position of the character, which was removed. It is displayed again as soon as the caret is moved before that text position again.

**Steps to reproduce**

1. Open SM in safe mode
2. Open a repository
3. Select the most recent commit
4. Start editing the commit message.

**Expected behavior**

Always show the caret.

**Screenshots**

![Animation](https://user-images.githubusercontent.com/16542113/91610913-6e0f4d80-e97a-11ea-893b-a660368fbfe5.png)

**Comment by BenjaminSchaaf** [comment] 2020-08-31 04:20
I can't reproduce this on the same version of Windows. I assume this still happens in safe mode? Do you have hardware_acceleration enabled? Are you seeing the same behaviour in other input boxes, like when writing a new commit message, resolving a merge conflict or editing preferences?

**Comment by deathaxe** [comment] 2020-08-31 16:58
It may be related with the number of lines and or the content of the commit message, I guess. Some kind of edge case. I can reproduce in safe mode, yes. Hardware acceleration is off.

It's the commit message of https://github.com/sublimehq/Packages/pull/2470/commits/d583f81dd16f944595b3003d56554bcac0ee7605 of PR https://github.com/sublimehq/Packages/pull/2470

If I select the commit and hit `ctrl+enter` to edit the commit message the caret disappears when hitting backspace and then right arrow at line 48 onwards. Opening SM in safe mode causes the caret to disappear at line 52 onwards. Don't know what's the reason for the difference though.

If I copy and paste the message into a new commit dialog, everything is fine. Staging any file, committing, then again editing the commit message -> same issue.

Not sure whether it is relevant, but the CSS folder is checked out in a separate worktree.

The main "Packages" repository is checked out at C:\Data\Sublime\Packages. CSS is at C:\Data\Sublime\Packages_CSS via `git worktree add ...` and `git sparse-checkout ...`, so the Package_CSS only contains a CSS sub directory.

With or without the following settings, I can reproduce the issue.

**Preferences**

```
{
	"always_show_commit_graph": false,
	"font_face": "iosevka light ultra-extended",
	"font_options":
	[
		"dwrite_cleartype_natural"
	],
	"font_size": 9,
	"git_binary": "system",
	"hide_menu": true,
	"line_padding_bottom": 2,
	"line_padding_top": 2,
	"theme": "Merge Dark.sublime-theme",
	"theme_font_options":
	[
		"dwrite_cleartype_natural"
	],
	"time_format": "system",
	"side_bar_layout": "commit_graph_as_column",
} 
```

**Comment by BenjaminSchaaf** [comment] 2020-09-01 07:58
Thanks, I was able to reproduce this on Linux as well. Seems to be window-height related and purely a rendering issue, as the caret re-appears once moved upwards again.

**Comment by BenjaminSchaaf** [comment] 2020-09-04 08:17
Should be fixed in build 4085

**Closed by BenjaminSchaaf** 2020-09-04 08:17 UTC
Labels: S: minor, bug
