### ISSUE TITLE
Text shadow rendering bug

### ISSUE THREAD

**Issue by genericptr** [sublimehq/sublime_merge#1458] opened 2022-04-04 03:01 UTC
**Version info**

 - OS: macOS 12.3 (Apple Sillicon)
 - Build: 2068

**Description**

I've seen this in other areas also but this just one example. 

<img width="281" alt="Screen Shot 2022-04-04 at 9 59 45 AM" src="https://user-images.githubusercontent.com/10937186/161466857-e3240a11-bb21-4b19-8905-b761bd9db25f.png">

**Comment by dpjohnst** [comment] 2022-04-06 02:15
Hi @genericptr,

Thanks for reporting this issue!

This issue should be fixed in Sublime Merge 2069 (development build), and will be fixed in the next stable build.

I'm going to close this issue, as it's a duplicate of https://github.com/sublimehq/sublime_merge/issues/1363
Feel free to subscribe to the linked issue above, as I'll update it once the fix has been released on the stable channel.

Cheers,
\- Dylan from Sublime HQ

**Closed by dpjohnst** 2022-04-06 02:15 UTC
