### ISSUE TITLE
Pop stash menu button tooltip is far away

### ISSUE THREAD

**Issue by AmjadHD** [sublimehq/sublime_merge#901] opened 2020-09-04 23:54 UTC
**Version info**

 - OS: Windows 10
 - Build: Dev Channel Build 2033

**Description**

when you hover over the pop stash menu button, the tooltip appears away

**Steps to reproduce**

1. make some changes to the workspace
2. stash them
3. see the screencast ⬇

**Expected behavior**

tooltip should be under the button

**Screenshots**

![pop_stash_tooltip_position](https://user-images.githubusercontent.com/33235928/92291579-ac2be480-ef19-11ea-8255-39c84b17382e.gif)

**Comment by dpjohnst** [comment] 2020-09-06 23:19
Hi @AmjadHD,

Thanks for reporting this. This looks like a duplicate of https://github.com/sublimehq/sublime_merge/issues/899, so I'm going to go ahead and close this one.

Please feel free to head over to the linked issue and subscribe to it to continue to receive updates on the issue.

Kind regards,
\- Dylan

**Closed by dpjohnst** 2020-09-06 23:19 UTC
