### ISSUE TITLE
Enable Snippets and Completions in Commit Message Editor

### ISSUE THREAD

**Issue by tajmone** [sublimehq/sublime_merge#599] opened 2019-10-21 05:53 UTC
It would be really nice if SM would support user-definable snippets and auto-completions in the Commit editor box.
This could spare a lot of typing, with ST-like snippets being able to provide templates for common messages and text-structures, with the usual Tab-navigation between elements.

Ideally, snippets and completions could be defined not only globally but also on a per-project base — either on the local user machine, or even within a repository, so that collaborators could share common snippets too.

The commit messages editor could benefit from many of ST3 features to enhance the typing experience; after all, it's a small editor in its own right.

**Comment by tajmone** [comment] 2019-10-21 05:56
Cf. SM Forum thread on this issue:

https://forum.sublimetext.com/t/enable-snippets-and-completions-in-commit-message-editor/47211

**Comment by omertuc** [comment] 2019-10-30 07:42
Duplicate of #339

**Closed** 2019-10-30 10:27 UTC

**Comment by omertuc** [comment] 2019-10-30 10:28
You can add your additional snippets suggestion as a comment on #339 :+1:
