### ISSUE TITLE
Regression: Commit message lines starting with # are treated as comments

### ISSUE THREAD

**Issue by abjugard** [sublimehq/sublime_merge#1320] opened 2021-11-08 08:57 UTC
**Version info**

 - OS: macOS 11.6
 - Build: 2063

**Description**

In previous builds, commit message lines starting with a # were correctly escaped when saving. In build 2063 they are treated as comments and ignored.

**Steps to reproduce**

1. Open any repository
2. Write a commit message including a # in the beginning of any line, e.g.
```
Changed the thing

#12345 <- ticket id to ensure commit is included in change logs etc.
```
3. Click on "Commit..."

**Expected behavior**

A commit added reflecting the entire message as entered in Sublime Merge.

**Actual behavior**

A commit added but all lines beginning with # are stripped from the message.

**Comment by srbs** [comment] 2021-11-08 12:33
duplicate of #1307

**Comment by dpjohnst** [comment] 2021-11-17 05:26
Hi @abjugard,

Thank you for reaching out. As @srbs mentioned this is a duplicate of #1307.
I'm going to go ahead and close this issue, but please take a look at the linked issue for the fix and further information.

(As a quick fix: `git config core.commentChar ";"` will change the comment character to `;`)

Thanks,
\- Dylan

**Closed by dpjohnst** 2021-11-17 05:26 UTC
