### ISSUE TITLE
Clicking a node of the log graph won't show modified files of the commit

### ISSUE THREAD

**Issue by Guilmo** [sublimehq/sublime_merge#298] opened 2018-12-05 17:06 UTC
**Version info**

 - OS: macOS 10.13.6
 - Build: 1092

**Description**

Clicking a node on the log graph won't expand the commit into the modified files as it did before build 1092. This might be the new expected behaviour, since the new Contents tab in the Locations Bar seems to show the same information, but I find this behaviour unintuitive and the information not as accessible as it was before:
- I spend a lot of time navigating between branches, and thus my Locations bar is primarily on the locations tab. It is not evident to me that the content that will be shown in the Contents tab is related to the commit selected in the graph.
- Expanding the commit in the log graph allow for quick and easy navigation of commits by simply using the arrows on the keyboard since the commit would get expanded or collapsed with the right and left arrows.

**Steps to reproduce**

1. Click the node of a commit on the log graph
**Result:** Nothing happens (except for a 'merge commit').
2. Select a commit
3. Press the right arrow on the keyboard
**Result:** Nothing happens (except for a 'merge commit').

**Expected behavior**

The list of modified files is shown when the node is clicked or the right arrow is pressed.

**Comment by dylanjohnston** [comment] 2018-12-06 00:48
Hi @Guilmo,

Thanks for your feedback! 

As you've noticed, we've moved the files view to the contents panel.
We've also added the `spacebar` keyboard shortcut to quickly toggle between the commit graph and the contents panel.

Let me know if this is useful for you.

Kind regards,

\- Dylan Johnston
Software Engineer, Sublime HQ

**Comment by srbs** [comment] 2018-12-06 00:49
See also #256

**Comment by wbond** [comment] 2019-01-02 21:00
Closing this as this is currently functioning as intended. Hopefully the available shortcut to switch in and out of the Contents view is sufficient.

**Closed by wbond** 2019-01-02 21:00 UTC
Labels: wontfix
