### ISSUE TITLE
Hunk History: other hunks may show when toggling ignore-whitespace

### ISSUE THREAD

**Issue by srbs** [sublimehq/sublime_merge#390] opened 2019-02-15 22:11 UTC
**Version info**

 - OS: macOS 10.14
 - Build: 1104 (initially noticed in 1099)

**Description**

When viewing hunk history, if ignore-whitespace is disabled _before_ viewing hunk history, toggling whitespace will show other hunks. If ignore-whitespace is enabled _before_, toggling whitespace will _not_ show other hunks.

**Steps to reproduce**

Commands to create an example test repos I used to reproduce:

    mkdir __test; cd __test
    git init
    
    printf "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n" > file.txt
    git add file.txt
    git commit -m initial
    
    printf "1\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n19\n20\n" > file.txt
    git commit -am broken-hunk-diff
    
    smerge .

1. create the repository above (shamelessly stolen from #389 where I found this bug)
2. navigate to that commit
3. disable ignore-whitespace (if enabled)
4. click hunk history for one hunk
5. toggle ignore-whitespace multiple times
    * notice other hunks appear & disappear based on ignore-whitespace state
6. exit hunk history
7. enable ignore-whitespace
8. click hunk history for one hunk
9. toggle ignore-whitespace multiple times
    * notice other hunk _do not_ appear

See video below for an example

**Expected behavior**

I would expect that other hunks should not appear/disappear when toggling ignore-whitespace.

**Screenshots**

![hunk-history-toggle-whitespace-behavior](https://user-images.githubusercontent.com/297298/52886901-7eb2f680-313b-11e9-9682-8aa4c7c3221b.gif)

**Comment by dpjohnst** [comment] 2019-03-12 04:58
Hi @srbs,

Thanks for the report!

I am currently investigating this issue and I have been able to reproduce the issue. I will let you know when a fix has been issued.

Kind regards,
\- Dylan Johnston
Software Engineer, Sublime HQ

**Comment by BenjaminSchaaf** [comment] 2020-06-09 06:26
Should be fixed since build 1108

**Closed by BenjaminSchaaf** 2020-06-09 06:26 UTC
Labels: bug
