### ISSUE TITLE
Image diff doesn't appear to show new version

### ISSUE THREAD

**Issue by adamscoble** [sublimehq/sublime_merge#1205] opened 2021-07-06 00:23 UTC
**Version info**

 - OS: Windows 10
 - Build: 0256

**Description**

More often than not the image diff doesn't actually show anything for the new version. Occasionally I can get it to show up, but I have no idea what I do to do it. Is it possibly using LFS related?

**Steps to reproduce**

Actually unsure. It's possible that it's related to LFS? But I am not 100% confident in that.

**Expected behavior**

It would show the new image.

**Screenshots**

![image-diff-bug](https://user-images.githubusercontent.com/3459709/124525832-149e6780-de44-11eb-9b4e-50fa8053cbe8.png)

**Comment by dpjohnst** [comment] 2021-07-06 01:29
Hi @adamscoble,

Thanks for the report - much appreciated!

When you have a spare moment, could you confirm a couple of things?
* What is the image format (file extension)?
* What is the file size of the new image?
* Are you using Git LFS to track this file?
* Could you share your debug information from Sublime Merge? This can be accessed via Help > Debug Information.
  Please take a moment to remove any sensitive information (emails, names, remotes, paths etc) before sharing.

Cheers,
\- Dylan

**Comment by adamscoble** [comment] 2021-07-06 01:47
Hey @dpjohnst !

- PNG
- 394 KB
- Yep, I'm using LFS
- Debug info is below, hopefully I didn't miss any sensitive information, and conversely I hope I didn't strip out anything useful! Haha:
`=== App Version Information ===
Build: 2056

=== Git Version Information ===
Using Git: C:\Program Files\Sublime Merge\Git\cmd\git.exe (bundled)
git version 2.30.2.windows.1
PATH: c:\programdata\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\gtksharp\2.12\bin;c:\program files\git\cmd;c:\windows\system32\openssh\;c:\bin\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\FileBot\;C:\Ruby27-x64\bin;C:\Users\<REMOVED>\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\<REMOVED>\AppData\Local\Programs\Python\Python38\;C:\Users\<REMOVED>\AppData\Local\Microsoft\WindowsApps;C:\FFmpeg\bin;

=== Browse Page Information ===
HEAD: <REMOVED>
Is in merge: 0
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===
<REMOVED>

=== Our Status Information ===
<REMOVED>

=== Git Config Information ===
branch.develop.merge=refs/heads/develop
branch.develop.remote=origin
color.branch=auto
color.diff=auto
color.interactive=true
color.status=auto
core.autocrlf=true
core.bare=false
core.filemode=false
core.fscache=true
core.ignorecase=true
core.logallrefupdates=true
core.repositoryformatversion=0
core.symlinks=false
credential.helper=manager
diff.astextplain.textconv=astextplain
difftool.sourcetree.cmd='' "$LOCAL" "$REMOTE"
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.smudge=git-lfs smudge -- %f
help.format=html
http.postbuffer=524288000
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
include.path=C:/Program Files/Git/etc/gitconfig
<REMOVED>
mergetool.sourcetree.cmd='' 
mergetool.sourcetree.trustexitcode=true
pack.packsizelimit=2g
rebase.autosquash=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
<REMOVED>
user.email=<REMOVED>
user.name=<REMOVED>

=== Our Config Information ===
Git Config Path Information
Using config path: /C/ProgramData/Git/config
Using config path: /C/Program Files/Sublime Merge/Git/etc/gitconfig
Using config path: /C/Users/<REMOVED>/.config/git/config
Using config path: /C/Users/<REMOVED>/.gitconfig
Using config path: /C/Game Development/<REMOVED>/.git/config

Our config output is different to the Git config output
branch.develop.merge=refs/heads/develop
branch.develop.remote=origin
color.branch=auto
color.diff=auto
color.interactive=true
color.status=auto
core.autocrlf=true
core.bare=false
core.filemode=false
core.fscache=true
core.ignorecase=true
core.logallrefupdates=true
core.repositoryformatversion=0
core.symlinks=false
credential.helper=manager
diff.astextplain.textconv=astextplain
difftool.sourcetree.cmd='' "$LOCAL" "$REMOTE"
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.smudge=git-lfs smudge -- %f
help.format=html
http.postbuffer=524288000
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
include.path=C:/Program Files/Git/etc/gitconfig
<REMOVED>
<REMOVED>
<REMOVED>
mergetool.sourcetree.cmd='' 
mergetool.sourcetree.trustexitcode=true
pack.packsizelimit=2g
rebase.autosquash=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
<REMOVED>
user.email=<REMOVED>
user.name=<REMOVED>

=== Git Attributes Information ===
git check_attr --all output
.gitignore
<REMOVED>

=== Our Modified Files Newline Normalisation and EOL Information ===
.gitignore: autocrlf - crlf
<REMOVED>

=== Our Modified Files Flag Information ===
Ignoring symlinks: 1
.gitignore: Working - Normal File : Index - Normal File
<REMOVED>`

**Comment by dpjohnst** [comment] 2021-07-06 02:26
Hi @adamscoble,

Thanks for the information - I've reproduced the issue and I am working on a fix.

Cheers,
\- Dylan

**Comment by adamscoble** [comment] 2021-07-06 03:19
That's awesome, thanks @dpjohnst!

**Comment by srbs** [comment] 2021-07-22 05:06
@adamscoble, looks like this was fixed in dev build 2058

**Comment by dpjohnst** [comment] 2021-07-28 01:49
Hi @adamscoble,

This was fixed in Sublime Merge Build 2058 (Dev) /2059 (Stable)!

Cheers,
\- Dylan from Sublime HQ

**Closed by dpjohnst** 2021-07-28 01:49 UTC
Labels: bug
