### ISSUE TITLE
Add a command to switch between light and dark theme

### ISSUE THREAD

**Issue by Zwyx** [sublimehq/sublime_merge#1407] opened 2022-02-01 13:10 UTC
**Problem description**

Switching between light and dark theme in Sublime Merge isn't quick: we have to open the Preferences dialogue.

**Preferred solution**

A command — to which we can associate a shortcut — to switch between light and dark theme would be great.

**Alternatives**

I have actually found a solution for this, but it's convoluted:

Create the file `~/.config/sublime-merge/Packages/User/switch-theme.sh`, containing:

```sh
prefsFile=$(dirname $0)/Preferences.sublime-settings

if grep -q "Merge.sublime-theme" $prefsFile; then
	sed -i \
		-e 's/^\t"theme":.*$/\t"theme": "Merge Dark.sublime-theme"/g' \
		$prefsFile
else
	sed -i \
		-e 's/^\t"theme":.*$/\t"theme": "Merge.sublime-theme"/g' \
		$prefsFile
fi
```

In `~/.gitconfig`:

```ini
[alias]
	switch-sublime-theme = !~/.config/sublime-merge/Packages/User/switch-theme.sh
```

Now we can create a command, in `~/.config/sublime-merge/Packages/User/Default.sublime-commands`:

```json
[
	{
		"caption": "Switch theme",
		"command": "git",
		"args": { "argv": ["switch-sublime-theme"] }
	}
]
```

And/or create a shortcut, in `~/.config/sublime-merge/Packages/User/Default (Linux).sublime-keymap`:

```json
[
	{
		"keys": ["alt+shift+t"],
		"command": "git",
		"args": { "argv": ["switch-sublime-theme"] }
	}
]
```

**Comment by dpjohnst** [comment] 2022-02-06 23:56
Hi @Zwyx,

Thanks for sharing this feedback!

I'm going to go ahead and close this issue as it's more-or-less a duplicate of https://github.com/sublimehq/sublime_merge/issues/703. That being said, please feel free to head over there and subscribe to the issue to keep up to date with any request updates.

Cheers,
\- Dylan from Sublime HQ

**Closed by dpjohnst** 2022-02-06 23:56 UTC

**Comment by Zwyx** [comment] 2022-02-07 04:39
Hi @dpjohnst and thanks for your message. It's indeed a duplicate... sorry for not having checked before posting it! I've wrote my alternative solution in #703.
