### ISSUE TITLE
`smerge .` always opens default sized window on MacOS

### ISSUE THREAD

**Issue by pshirshov** [sublimehq/sublime_merge#611] opened 2019-11-07 14:34 UTC
1. Build: 1119
2. MacOS 10.15.1

The window which opens after I run `smerge .` in terminal is always default sized and does not remember last used settings. At the same time it's okay when I run just `smerge`.

Though it's inconvenient because sometimes I wish to run `smerge reponame` and I always have to manually resize SM window after that.

Also it would be great to have a config option to override default window size/

**Comment by chrisjbillington** [comment] 2019-11-27 19:58
Duplicate of #396

**Comment by dpjohnst** [comment] 2020-11-01 23:37
Hi @pshirshov,

Thank you for reporting this.

As this is a duplicate of #396, I'm going to go ahead and close this.
Please feel free to subscribe to issue #396 so you can continue to receive updates on the issue.

Kind regards,
\- Dylan

**Closed by dpjohnst** 2020-11-01 23:37 UTC
