### ISSUE TITLE
Squashing commit onto parent commit does not seem to be working

### ISSUE THREAD

**Issue by sujitha-jose** [sublimehq/sublime_merge#416] opened 2019-03-14 10:20 UTC
**Version info **

 - OS: Windows 10
 - Build: 1107

**Description**

Under edit commit, when I try to squash a single commit with a parent commit, it doesn't say anything if its successful or not, nor do I see any squash happening.

**Steps to reproduce**

1. Create two commits.
2. On the latest commit, Edit commit -> Squash with parent

**Expected behavior**

There should be a single commit.

**Screenshots**

If applicable, add screenshots to help explain your problem. This section may be omitted/removed.

**Comment by dpjohnst** [comment] 2021-10-08 04:00
I'm going to close this, as I cannot reproduce this issue and it's quite an old report.
If this is still present on your end, feel free to re-open the issue and I can investigate further.

Thanks,
\- Dylan from Sublime HQ

**Closed by dpjohnst** 2021-10-08 04:00 UTC
