### ISSUE TITLE
Crash On Launch - Mac 10.11.6 - Build: Any

### ISSUE THREAD

**Issue by MonatomicXenon** [sublimehq/sublime_merge#205] opened 2018-10-31 09:10 UTC
**Version info**
 - OS: Mac 10.11.6
 - Build: Any (including 1084)

**Description**
App crashes immediately upon launch, UI doesn't even load.

**Steps to reproduce**

Launch application.

**Expected behavior**
Successful launch.

**Screenshots**
![image](https://user-images.githubusercontent.com/33680946/47777495-12a6a280-dcb2-11e8-94f4-76ea854a5f76.png)

**Comment by rchl** [comment] 2019-02-26 19:08
I had this issue on one Mac before but it fixed itself there.

On another Mac, where it was always crashing on startup, I have sat and figured it out. On very first start it would show the app window but in broken state and error dialog:
![screenshot 2019-02-26 at 20 02 15](https://user-images.githubusercontent.com/153197/53439155-b8201780-3a01-11e9-947e-d7a7eac6fe03.png)

Trying to start it again after that would just crash instantly without showing app window.

Deleting app's settings with:
```
rm -rf ~/Library/Application\ Support/Sublime\ Merge && rm -rf ~/Library/Caches/com.sublimemerge
```
would make it show the broken app dialog again one time.

What actually fixed it was:
1. deleting its settings with above command
2. Moving Sublime's Text settings to some other place:
```
mv ~/Library/Application\ Support/Sublime\ Text\ 3/ ~/Library/Application\ Support/Sublime\ Text\ 3.bak/
```
3. Starting Sublime Merge

After doing that, SM would start and I could rename back Sublime's Text settings back to original location and SM would keep working.

So some ST settings/files are causing SM to crash on startup. I could provide those to devs (possibly try to minimize a bit first).

**Comment by rchl** [comment] 2019-02-26 19:19
It seems like it might be just about the number of files in `~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages\` directory. With 75 files SM starts fine. With 76 it shows broken window as on screenshot but without "Error loading syntax" dialog. With 79 files or move it also shows the syntax loading dialog.

**Comment by presidenten** [comment] 2019-05-06 06:57
I have 7 files in that directory and Sublime merge wont even start. No crash info or anything.
Running osx 10.14.4 and sublime merge build 1107.

**Comment by drcongo** [comment] 2019-05-10 08:51
I just downloaded Sublime Merge for the first time and got the exact same error as @rchl. I have `~/Library/Application\ Support/Sublime\ Text\ 3` symlinked to a folder in Dropbox so that I can keep the exact same config when switching between computers, I'm guessing this has something to do with that.

![Screen Shot 2019-05-10 09 45 37 AM](https://user-images.githubusercontent.com/39289/57514728-fe9ac800-7308-11e9-87f9-c88972c790fb.png)

**Comment by rchl** [comment] 2019-05-10 09:12
In my case, I also have symlink but for `Packages` only, not whole `Sublime Text 3` folder.
Also, from my experiments above, it seems like it's related to contents of `Installed Packages`.

**Comment by dpjohnst** [comment] 2020-07-06 01:53
Hi all, 

Just wanted to follow up on this issue to see if anyone was still affected by it?

Thanks,
\- Dylan

**Comment by drcongo** [comment] 2020-07-07 11:53
@dpjohnst No, all working here these days.

**Comment by rchl** [comment] 2020-08-24 07:56
I don't have that issue anymore but also I don't have the same setup anymore. I've just tried to artificially implode the number of installed packages and it didn't reproduce but I'm not sure if that's because there is something different about this setup or because the issue is fixed.

Thus I'm fine with closing this.

**Closed** 2023-08-11 04:14 UTC
Labels: bug
