### ISSUE TITLE
"Edit commit contents" loses authorship

### ISSUE THREAD

**Issue by tomba** [sublimehq/sublime_merge#1125] opened 2021-04-29 06:11 UTC
**Version info**

 - OS: Ubuntu 20.04
 - Build: 2050

**Description**

When editing a commit with "Edit commit contents" sublime merge loses the authorship information and uses the current committer as author. In other words, if you, say, fix a typo in a commit authored by someone else, the author will be overwritten with the current committer.

This is different than how git rebase -i works, where you (usually) append changes to an existing commit, and the authorship is kept.

**Steps to reproduce**

1. Have a commit in history authored by someone else
2. Use "Edit commit contents" to edit it.
3. Click commit button

**Expected behavior**

Author of the commit stays the same.

**Comment by srbs** [comment] 2021-04-29 09:24
duplicate of #728

**Comment by dpjohnst** [comment] 2021-04-30 05:31
Hi @tomba,

Thanks for sharing this feedback!

As @srbs has pointed out, this is a duplicate of an existing issue so I'm going to go ahead and close this one.
Feel free to head over to the issue that @srbs linked to keep up to date with it!

Kind regards,
\- Dylan

**Closed by dpjohnst** 2021-04-30 05:31 UTC
