### ISSUE TITLE
Under Rosetta 2, text characters disappear during scrolling & mouse movement

### ISSUE THREAD

**Issue by unitof** [sublimehq/sublime_merge#1024] opened 2021-01-02 04:05 UTC
**Version info**

 - OS: macOS 11.1 (but experienced since 11.0)
 - Build: 2041
 - Hardware: MacBook Pro (13-inch, M1, 2020)

**Description**

When running on an Apple Silicon Mac under Rosetta 2, in the primary pane, seemingly random characters of text disappear and reappear depending on cursor position, scroll position, and window size.

Full text (including the disappeared characters) is still copied when text is highlighted while bug is present.

I have experienced this bug on a variety of repositories using every latest version of Sublime Merge since November 19, 2020 (when I set up my M1 MacBook Pro).

**Screenshots**

#### In Blame view
<img width="1443" alt="Screen Shot 2021-01-01 at 10 48 29 PM" src="https://user-images.githubusercontent.com/2448782/103450417-0ba9bf00-4c84-11eb-92c9-423429c6c06a.png">
<img width="1443" alt="Screen Shot 2021-01-01 at 10 48 31 PM" src="https://user-images.githubusercontent.com/2448782/103450418-0ea4af80-4c84-11eb-8cb0-a277c03c993b.png">

https://user-images.githubusercontent.com/2448782/103450438-693e0b80-4c84-11eb-88cd-3f5941b5344d.mov

#### In Commit view
<img width="1443" alt="Screen Shot 2021-01-01 at 10 48 48 PM" src="https://user-images.githubusercontent.com/2448782/103450420-1a907180-4c84-11eb-942c-0038d948ce22.png">
<img width="1443" alt="Screen Shot 2021-01-01 at 10 48 50 PM" src="https://user-images.githubusercontent.com/2448782/103450421-1cf2cb80-4c84-11eb-8d9e-50cc016e7dd0.png">

https://user-images.githubusercontent.com/2448782/103450479-0c8f2080-4c85-11eb-93f0-4f5cb22337fe.mov

**Debug Information**

```
=== App Version Information ===
Build: 2041

=== Git Version Information ===
Using Git: git (system)
git version 2.24.3 (Apple Git-128)
PATH: /usr/local/Caskroom/miniconda/base/bin:/Users/jacob/bin:/usr/local/opt/python/libexec/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/sbin (from shell)
environment variables loaded using: /bin/zsh -l

=== Browse Page Information ===
HEAD: e5eb6a264669afdf6e3def98c967509874501d95
Is in merge: 0
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===

=== Our Status Information ===

=== Git Config Information ===
alias.ci=commit
alias.cp=cherry-pick --no-commit
alias.logol=log --oneline
alias.lograph=log --graph --all --decorate
alias.root=rev-parse --show-toplevel
alias.st=status
branch.add-arch-blocks.merge=refs/heads/add-arch-blocks
branch.add-arch-blocks.remote=fork-unitof
branch.master.merge=refs/heads/master
branch.master.remote=origin
core.autocrlf=false
core.bare=false
core.excludesfile=/Users/jacob/.gitignore_global
core.filemode=true
core.ignorecase=true
core.logallrefupdates=true
core.precomposeunicode=true
core.repositoryformatversion=0
credential.helper=osxkeychain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.smudge=git-lfs smudge -- %f
ghi.token=17abc99e58de733103ee4ccf1960b596da115d64
homebrew.analyticsmessage=true
homebrew.analyticsuuid=7F16F8EC-FB43-4D72-B613-95778494B61D
homebrew.caskanalyticsmessage=true
homebrew.devcmdrun=true
homebrew.donationmessage=true
homebrew.latesttag=2.7.1
init.defaultbranch=main
pager.branch=false
pull.ff=only
push.default=current
remote.fork-unitof.fetch=+refs/heads/*:refs/remotes/fork-unitof/*
remote.fork-unitof.url=git@github.com:unitof/brew.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.gh-resolved=base
remote.origin.url=https://github.com/Homebrew/brew
user.email=j@cobford.com
user.name=Jacob Ford

=== Our Config Information ===
Git Config Path Information
Using config path: /etc/gitconfig
Using config path: /Users/jacob/.config/git/config
Using config path: /Users/jacob/.gitconfig
Using config path: /opt/homebrew/.git/config

Our config output is different to the Git config output
alias.ci=commit
alias.cp=cherry-pick --no-commit
alias.logol=log --oneline
alias.lograph=log --graph --all --decorate
alias.root=rev-parse --show-toplevel
alias.st=status
branch.add-arch-blocks.merge=refs/heads/add-arch-blocks
branch.add-arch-blocks.remote=fork-unitof
branch.master.merge=refs/heads/master
branch.master.remote=origin
core.autocrlf=false
core.bare=false
core.excludesfile=/Users/jacob/.gitignore_global
core.filemode=true
core.ignorecase=true
core.logallrefupdates=true
core.precomposeunicode=true
core.repositoryformatversion=0
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.smudge=git-lfs smudge -- %f
ghi.token=17abc99e58de733103ee4ccf1960b596da115d64
homebrew.analyticsmessage=true
homebrew.analyticsuuid=7F16F8EC-FB43-4D72-B613-95778494B61D
homebrew.caskanalyticsmessage=true
homebrew.devcmdrun=true
homebrew.donationmessage=true
homebrew.latesttag=2.7.1
init.defaultbranch=main
pager.branch=false
pull.ff=only
push.default=current
remote.fork-unitof.fetch=+refs/heads/*:refs/remotes/fork-unitof/*
remote.fork-unitof.url=git@github.com:unitof/brew.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.gh-resolved=base
remote.origin.url=https://github.com/Homebrew/brew
user.email=j@cobford.com
user.name=Jacob Ford

=== Git Attributes Information ===
git check_attr --all output

=== Our Modified Files Newline Normalisation and EOL Information ===

=== Our Modified Files Flag Information ===
Ignoring symlinks: 0
```

**Comment by srbs** [comment] 2021-01-04 20:58
Do you have Hardware Acceleration enabled? (Settings > Advanced)

Does it still happen when you switch that setting?

**Comment by samsamoa** [comment] 2021-01-06 04:06
I have this issue as well.  I disabled Hardware Acceleration as suggested above, and the glitch is gone.

**Comment by dpjohnst** [comment] 2021-01-10 23:44
Hi @samsamoa,

Thanks for reporting this issue. As mentioned, disabling hardware acceleration is the best workaround currently.

As it's a duplicate of https://github.com/sublimehq/sublime_merge/issues/1018, I'm going to go ahead and close this issue.
Feel free to subscribe to the linked issue to continue to receive any further updates on this issue.

Kind regards,
\- Dylan

**Closed by dpjohnst** 2021-01-10 23:44 UTC

**Comment by unitof** [comment] 2021-01-10 23:47
Indeed hardware acceleration had been on (OpenGL) and so far I haven't seen it after switching off.

Will you likely update this ticket when this is fixed on Apple Silicon, so I know turn to hardware acceleration back on? Thanks!

**Comment by srbs** [comment] 2021-01-11 05:02
@unitof, this issue will likely not get updated, but you can subscribe for updates on #1018.
