### ISSUE TITLE
Allow Sublime Merge to open (or create) Pull Requests / Merge Requests

### ISSUE THREAD

**Issue by arianf** [sublimehq/sublime_merge#293] opened 2018-12-04 21:50 UTC
**Problem description**

I currently use `git open`: https://github.com/paulirish/git-open to do this in the command line, it would be great if sublime merge supported this out of the box. When you can open the repo in GitHub or GitLab depending on your remote origin url.

**Comment by srbs** [comment] 2018-12-06 03:34
See also #42 & https://forum.sublimetext.com/t/checkout-pr/40495

**Comment by wbond** [comment] 2019-01-02 20:56
This seems to be a duplicate of #267

**Closed by wbond** 2019-01-02 20:56 UTC
