### ISSUE TITLE
Stage/Discard for single lines doesn't work

### ISSUE THREAD

**Issue by dva** [sublimehq/sublime_merge#881] opened 2020-08-25 15:55 UTC
**Version info**

 - OS: macOS 10.15.2
 - Build: 2032

**Description**

Selecting a line with further Stage/Discard produces `Failed to apply patch: no modified lines selected`.

**Steps to reproduce**

1. Create and commit complex package.json (e.g. from [ReactJS](https://raw.githubusercontent.com/facebook/react/master/package.json))
2. Make some random changes to devDependencies versions like on screen below.
3. In Side-by-Side view mode try to select one line and Stage/Discard it.

**Expected behavior**

Single line should be able to be Stage/Discarded in Side-by-Side view mode like it was on build 2027.

**Screenshots**

![Kapture 2020-08-25 at 18 31 42 2020-08-25 18_47_53](https://user-images.githubusercontent.com/365010/91197041-8c1f4880-e703-11ea-8e92-e5bcb36656f3.gif)

**Comment by srbs** [comment] 2020-08-25 21:48
possible duplicate of #866 

related to #878, #865

**Comment by dpjohnst** [comment] 2020-08-26 01:34
Hi @dva,

Thank you for reporting this issue. I've managed to replicate the issue using your instructions, and I can now confirm this is indeed a duplicate of #866.

The good news is I have a pending fix for this issue!

Now that it's confirmed as a duplicate, I'm going to go ahead and close this issue. Please feel free to move over to #866 to continue to receive updates regarding this issue :)

Thanks again for reporting this issue,
\- Dylan

**Closed by dpjohnst** 2020-08-26 01:34 UTC
Labels: bug
