### ISSUE TITLE
Opening a local repository with a "clean" filter hangs the app.

### ISSUE THREAD

**Issue by manubop** [sublimehq/sublime_merge#1104] opened 2021-03-24 11:13 UTC
**Version info**

 - OS: Windows 10
 - Build: 2049

**Description**

When I open a local repository with a "clean" filter, the top line of "Commits" column is stuck at "Loading changes...". Any further action on the same tab is ignored. Process remains in memory after application is closed and has to be killed manually.

NB: This behavior did not occur with previous build.

**Steps to reproduce**

1. Set git filter on a repository:
```
[filter "ignoreinject"]
	clean = sed '/inject:js/,/endinject/{//!d}'
```
2. Have one or more source files containing the following lines:
``` 
<!-- inject:js -->
...
<!-- endinject -->
``` 
3. Open repository.

**Expected behavior**

UI remains responsive.

**Screenshots**

![image](https://user-images.githubusercontent.com/6574242/112300070-c13f4980-8c98-11eb-9855-dc7f0af3686c.png)

**Comment by axi-jhkn** [comment] 2021-04-12 10:18
**Version info**
OS: Windows 10
Build: 2049
Description

**Description**
Me and my colleagues are experiencing the samen behaviour.
In our repository we are removing some comments automatically.

**Steps to reproduce**
Make sure you have the following files in the root of your repository
.gitconfig
`[filter "pck"]
  clean = grep -v -E \"^ \\*   (Project    |Version    |Language   |Date       |User       |PRC type   |PRC version) :\"`

.gitattributes
`**/packages/*.sql       filter=pck`

After downloading the repository for the first time we have to execute te following once
`git config --local include.path ../.gitconfig`

Create a folder "packages" in the root of your repository
And create the following file packages/PCK_DUMMY.sql
`
CREATE OR REPLACE EDITIONABLE PACKAGE "PCK_DUMMY" 
as
/**
 *  <pre>
 *   Project     : XXXX Development
 *   Class       : DUMMY -- Dummy
 *   Version     : unknown
 *   Language    : 1
 *   Date        : maandag   12-apr-2021 12:04
 *   User        : xxxx
 *   PRC type    : Model-based PL/SQL generator
 *   PRC version : release 1.22
 *  </pre>
 */

  procedure DUMMY;

end pck_dummy;

/
`

Open sublime merge and stage the change. Sublime Merge becomes unresponsive. 

**Expected behavior**
Comments in the file packages/PCK_DUMMY.sql are removed after staging.
`
CREATE OR REPLACE EDITIONABLE PACKAGE "PCK_DUMMY" 
as
/**
 *  <pre>
 *   Class       : DUMMY -- Dummy
 *  </pre>
 */

  procedure DUMMY;

end pck_dummy;

/
`

The reason to do this is because we only want to see the real changes and not the changes our code generator makes in its comments.

**Comment by manubop** [comment] 2021-05-05 12:42
Still not working with build 2054

**Comment by dpjohnst** [comment] 2023-02-06 23:37
Fixed in Sublime Merge 2083 (stable)

**Closed by dpjohnst** 2023-02-06 23:37 UTC
