### ISSUE TITLE
Deleted files come back on rebase

### ISSUE THREAD

**Issue by humancopy** [sublimehq/sublime_merge#1041] opened 2021-01-18 21:58 UTC
**Version info**

 - OS: [macOS 11.1]
 - Build: [2039]

**Description**

When you have a branch that deleted some file and if this file was changed in master on a later commit, when rebasing and resolving the conflicts either with ours or theirs the file comes back and if resolving with take right it comes back an empty file.

Checked with other git clients and they do it as expected.

**Steps to reproduce**

1. Create repository
2. Commit one file with some text
3. Create new branch
4. Delete file
5. Go back to master
6. Edit file and commit
7. Go back to new branch
8. Rebase with master
9. Try to resolve conflict and having the file stay deleted

**Expected behavior**

The file will be deleted.

**Comment by srbs** [comment] 2021-01-19 08:26
This should be a duplicate of #124 (and possibly #55)

**Comment by humancopy** [comment] 2021-01-19 09:40
Those bugs are from over 2 years ago, maybe time to fix? 🤣

**Comment by dpjohnst** [comment] 2021-01-20 00:14
Hi @humancopy,

Thank you for reporting this issue.

I'm going to go ahead and close this one as it's a duplicate, but feel free to move to (and subscribe to) issue #124.
I'll be sharing updates on that issue.

Kind regards,
\- Dylan

**Closed by dpjohnst** 2021-01-20 00:14 UTC
Labels: bug
