### ISSUE TITLE
Allow quick copy of commit hash and branch name

### ISSUE THREAD

**Issue by 1nv** [sublimehq/sublime_merge#832] opened 2020-07-22 11:40 UTC
**Problem description**

Often, there's a need to quickly copy commit hash and branch name. Currently, this can be done via the context menu of the '...' button to the right. However, it is inconvenient as the button is far away and the entries for these actions are well-hidden somewhere in the middle of the menu.

**Preferred solution**

Allow copying the hash and branch names by clicking on the hash and branch names entries respectively. Make the fields read-only text-fields so that they could also be selected and copied via standard OS hotkeys (Ctrl+C).

**Alternatives**

Allow copying the hash and branch names by right clicking them and selecting 'Copy' under context menu.

**Comment by srbs** [comment] 2020-07-22 18:11
duplicate of #716 & #580

**Comment by dpjohnst** [comment] 2020-07-24 00:29
Hi @1nv,

Thanks for sharing this feature request.

As is mentioned above, it looks like we have an existing request for this.
For that reason I'm going close this issue, but please don't hesitate to subscribe to one of the linked issues above.

Thanks,
\- Dylan

**Closed by dpjohnst** 2020-07-24 00:29 UTC
