### ISSUE TITLE
Search Query Syntax

### ISSUE THREAD

**Issue by psimek12** [sublimehq/sublime_merge#1263] opened 2021-09-14 12:59 UTC
**Problem description**

I would like to have a possibility to search in specific branch only. For example when I'm looking for changes from specific persion, I type author: <person_name>

This shows me all his commits. But I see all commits of this person in all branches. I would like to search in specific branch.

**Preferred solution**

branch: <branch_name>

**Alternatives**

?

**Screenshots**

**Comment by srbs** [comment] 2021-09-14 22:23
duplicates: #352, #492
related: #572, #597

**Comment by dpjohnst** [comment] 2021-09-16 04:49
Hi @psimek12,

Thanks for sharing this feedback!

As @srbs mentioned, this is a duplicate of #352 so I'm going to go ahead and close this one.
Please feel free to head over to the linked issue and give it a thumbs up / subscribe to stay updated on its status!

Thanks,
\- Dylan

**Closed by dpjohnst** 2021-09-16 04:49 UTC

**Comment by psimek12** [comment] 2021-09-16 05:11
Thanks Dylan, what are thé chances to have this implemented please?

Nice day
Petr

Dne čt 16. 9. 2021 6:49 uživatel Dylan Johnston ***@***.***>
napsal:
