### ISSUE TITLE
Artifacts when typing in text fields

### ISSUE THREAD

**Issue by TarekSalama** [sublimehq/sublime_merge#817] opened 2020-07-07 18:45 UTC
**Version info**

 - OS: macOS 10.15.5
 - Build: 2020

**Description**

On my MacBook Pro Early 2015 model, when hardware acceleration is enabled, when typing in any text field, I get weird artifacts as seen here https://imgur.com/a/eMdvRe7.

**Steps to reproduce**

I am not sure how to reproduce this other than simply reopening the app and noticing the issue.
I'd like to add that on a 2017 MacBook Pro that I have, this issue doesn't happen. Also turning off Hardware Acceleration helps with this issue. 
This issue doesn't happen in any other apps that I have so I doubt it's related to my CPU. 
Both MacBooks don't have a dedicated GPU.

**Expected behavior**

No artifacts when typing.

**Screenshots**

https://imgur.com/a/eMdvRe7

**Comment by srbs** [comment] 2020-07-08 05:27
duplicates #747 

@TarekSalama, workaround for now is turning off hardware acceleration.

**Comment by dpjohnst** [comment] 2020-07-11 05:18
Hi @TarekSalama,

Thank you for reporting this issue. As @srbs mentioned, this is a duplicate of an existing report, so I'll be closing this one.

Please feel free to subscribe to the linked bug report to ensure you continue to receive updates regarding the bug.

Kind regards,
\- Dylan

**Closed by dpjohnst** 2020-07-11 05:18 UTC
