### ISSUE TITLE
Text rendering of subtitles in Locations tab is a little wonky

### ISSUE THREAD

**Issue by sbdchd** [sublimehq/sublime_merge#1381] opened 2021-12-25 16:15 UTC
**Version info**

 - OS: macOS 19.4.0
 - Build: 2068

**Description**

Text for the subtitles in the locations tab has some rendering artifacts.

**Steps to reproduce**

1. Open repository
2. Navigate to locations tab
3. See rendering artifacts

**Expected behavior**

Clean, crisp text

**Screenshots**

<img width="399" alt="Screen Shot 2021-12-25 at 11 14 58 AM" src="https://user-images.githubusercontent.com/7340772/147389135-0af15051-e3b7-494c-8435-d18b419a6f1d.png">

**Comment by srbs** [comment] 2021-12-26 08:39
possible duplicate: #1363

**Comment by dpjohnst** [comment] 2022-01-10 23:55
Hi @sbdchd,

Thanks for reporting this issue!

As mentioned by @srbs, this is a duplicate of #1363. I'm going to close this issue, but feel free to subscribe to the linked issue to ensure you receive any updates on it.

Kind regards,
\- Dylan from Sublime HQ

**Closed by dpjohnst** 2022-01-10 23:55 UTC
