### ISSUE TITLE
Symlinks in windows appear as modified files

### ISSUE THREAD

**Issue by bempelise** [sublimehq/sublime_merge#813] opened 2020-06-29 16:36 UTC
**Version info**

 - OS: Windows 10
 - Build: 2020
 - git version: 2.25.1.windows.1

**Description**

When a symlink is used in a repository running git status on the bash console yields no changes:

```
$ git status
On branch release
nothing to commit, working tree clean
```

but when opening the same repository in sublime merge the symlink appears as a pending change:

**Steps to reproduce**

1. Create a unix symlink in a repository (in a linux machine)

2. Clone the repository in windows.
To make symlinks work in windows you need to make sure you have Developer Mode enabled. To do that go to `Windows settings`, search for `developer settings` and select `Developer mode`. Then clone the repository as usual. I think without developer mode, admin rights are needed and it gets messy.

If you have already cloned the repo before changing the `Developer mode` setting you will need to change the `symlinks` git configuration of the repository which will have defaulted to false due to failure:
Open `<repo>/.git/config` and change the `symlinks` setting to true and do a `git checkout path/to/symlink` to get the symlink.

To make sure you got the symlink as expected, when running `ll` on the folder containing the symlink you shoulg get the expected unix symlink annotation:
```
<symlink name> -> <path to folder>
```

3. Running `git status` on the git bash console should return empty. Launching sublime merge on the same repo should indicate the symlink as a pending change.

**Expected behavior**

Sublime Merge should indicate no changes.

**Screenshots**
Sample symlink appearing as a change in one of my repositories:

![image](https://user-images.githubusercontent.com/1123817/86031460-bfa86400-ba2d-11ea-8d2e-3d918421be70.png)

**Comment by stinos** [comment] 2020-06-29 16:37
Is this different from https://github.com/sublimehq/sublime_merge/issues/292 ?

**Comment by bempelise** [comment] 2020-06-29 16:46
I think it is a duplicate, sorry I did not find the other one...

**Comment by dpjohnst** [comment] 2020-06-30 06:21
Hi @bempelise,

Thanks for reporting this issue.

As it's a duplicate of an existing one, I'm going to close this one and continue on the existing issue.
Please go ahead and subscribe to (or comment on) #292 to continue to receive further updates on the issue.

Thanks,
\- Dylan

**Closed by dpjohnst** 2020-06-30 06:21 UTC
Labels: duplicate
