### ISSUE TITLE
clone tries to create an invalid directory

### ISSUE THREAD

**Issue by direbroom** [sublimehq/sublime_merge#197] opened 2018-10-28 17:35 UTC
**Version info**

 - OS: Windows 7
 - Build: 1083

**Description**

When trying to clone a new repo, sublime merge will automatically create a directory derived from the repo link. this can be an invalid directory when using a link like:
git@1.1.1.1:test

and there is no way to manually change that.

**Steps to reproduce**

1. Clone a repo with something like: git@1.1.1.1:test
2. Look at the Destination Path window
3. Click on Clone

**Expected behavior**

Correctly resolve the repository path from this URL syntax (and add an option for manual override of the destination path)

**Screenshots**

![image](https://user-images.githubusercontent.com/9298404/47619545-503edc00-dab6-11e8-8fd9-e729822908c2.png)

**Comment by srbs** [comment] 2018-11-21 19:34
Note: customization of destination directory is now possible in dev build 1088

**Comment by wbond** [comment] 2019-01-02 15:57
It would appear the issue is that the scp-like URL is not being recognized/parsed as an SSH URL. If that was the case, the suggested directory would be `test`.

**Comment by direbroom** [comment] 2019-02-02 19:59
There seems to be an additional issue (however I don't know yet if it's due to the url parsing or if it's a general problem):
1) start sublime merge and select clone repo
2) it has some default path in the dest path
3) change the dest path
4) start typing in source url which immediately reverts the dest path to what was there before
5) finish typing the src url
6) change dst path again and hit clone
7) behind my back it cloned into the dest path it started up with, _not_ what's written in the dest path

(this is not 100% I just stumbled over it today when cloning a few repositories and saw that they ended up in the wrong directory)

**Comment by dpjohnst** [comment] 2020-09-22 04:21
Hi all,

Closing as the original issue has been resolved.

Kind regards,
\- Dylan

**Closed by dpjohnst** 2020-09-22 04:21 UTC
Labels: bug, remotes
