### ISSUE TITLE
Filter commits on branch

### ISSUE THREAD

**Issue by bgeron** [sublimehq/sublime_merge#492] opened 2019-05-13 20:23 UTC
**Problem description**

I would like to search within my master branch, because my master branch contains good commits and other branches sometimes contain lots of half-baked experiments.

**Preferred solution**

A new search filter `on:branch` which returns true for commits that are reachable from `refs/heads/branch`.

**Alternatives**

None considered.

**Comment by dpjohnst** [comment] 2021-09-16 04:47
Hi all,

Closing this issue, as it's a duplicate of https://github.com/sublimehq/sublime_merge/issues/352

Feel free to head over to that issue and subscribe / thumbs up to stay updated on its status.

Cheers,
\- Dylan

**Closed by dpjohnst** 2021-09-16 04:47 UTC
