### ISSUE TITLE
Display Lines added/removed in commits, like on Github

### ISSUE THREAD

**Issue by vis2k** [sublimehq/sublime_merge#346] opened 2019-01-16 19:54 UTC
**Problem description**

It's very useful to see if a commit simplifies the code base or not, by seeing lines of code added+removed amounts.

**Preferred solution**

Display something similar to Github:
![image](https://user-images.githubusercontent.com/16416509/51274961-dd684180-19d0-11e9-8251-030f8f1d0b3f.png)

**Comment by srbs** [comment] 2019-01-16 21:07
Possible duplicate of #224

**Comment by dpjohnst** [comment] 2021-10-08 04:36
Closing, as this was added in Sublime Merge Build 2004

**Closed by dpjohnst** 2021-10-08 04:36 UTC
Labels: enhancement, ux, commit detail
