### ISSUE TITLE
Multi-select in the Files panel

### ISSUE THREAD

**Issue by adamscoble** [sublimehq/sublime_merge#1163] opened 2021-05-31 02:41 UTC
**Problem description**

It would be nice being able to use Ctrl/Shift to multi-select files in the File panel to select multiple, in order to stage (or unstage) multiple at a time.

**Preferred solution**

As above, selecting multiple files and then being able to use the regular commands would be lovely.

**Comment by dpjohnst** [comment] 2021-05-31 05:41
Hi @adamscoble,

Thanks for sharing this feedback with us - much appreciated!

This happens to be a duplicate of https://github.com/sublimehq/sublime_merge/issues/381, so I'm going to go ahead and close this issue. That being said, please feel free to head over to the linked issue and subscribe to (or comment on) it to ensure you receive any updates/announcements on the enhancement.

Thanks,
\- Dylan

**Closed by dpjohnst** 2021-05-31 05:41 UTC
