### ISSUE TITLE
Sublime Merge ignores first line of .gitignore file (if it has a BOM)

### ISSUE THREAD

**Issue by fschoenm** [sublimehq/sublime_merge#431] opened 2019-03-15 12:22 UTC
**Version info**

 - OS: Windows 10 (also Ubuntu 18.10)
 - Build: 1107

**Description**

The very first line of a .gitignore file is ignored and a file that should be ignored is shown in the Untracked Files list. Just adding an empty line as the first line is enough to correctly ignore the file.

**Steps to reproduce**

1. Create any file in the repository.
2. Put the filename in the first line of .gitignore.
3. Watch "Untracked Files".
4. Insert a new line at the beginning of the .gitignore file.
5. Watch the previously not ignored file disappear from "Untracked Files".

**Expected behavior**

.gitignore is correctly applied.

**Comment by BenjaminSchaaf** [comment] 2019-03-18 01:11
I can't reproduce this on Ubuntu 18.04:

```bash
$ git init
$ touch foo.txt
$ echo foo.txt > .gitignore
$ smerge .
```

Only has the `.gitignore` file as untracked.

**Comment by fschoenm** [comment] 2019-03-18 08:16
That's true. There seems to be something else going on. You can try with my original .gitignore:

[_gitignore.txt](https://github.com/sublimehq/sublime_merge/files/2976984/_gitignore.txt)

**Comment by fschoenm** [comment] 2019-03-18 08:19
I think I found the issue: my .gitignore file had a BOM and Sublime Merge seems to not be able to handle it correctly while git itself can. If I remove the BOM, the file will be ignored in Sublime Merge too.

**Comment by jskinner** [comment] 2019-03-19 01:19
Thanks for tracking the issue down @fschoenm, we'll fix that for the next build

**Comment by jskinner** [comment] 2019-03-21 00:46
This is now fixed in 1109, at https://www.sublimemerge.com/dev

**Closed by jskinner** 2019-03-21 00:46 UTC
