### ISSUE TITLE
Filter working directory

### ISSUE THREAD

**Issue by mheckel** [sublimehq/sublime_merge#656] opened 2020-02-04 16:16 UTC
**Problem description**

Sometimes I have a long list of uncommitted changes or untracked files. It would be helpful to easily filter the list.

**Preferred solution**

Some sort of a filtering mechanism (parts of filename, but maybe also date, etc.)

**Alternatives**

The recently changed symbol is helping, but filtering would be much easier on the eyes.

**Comment by srbs** [comment] 2020-02-08 06:19
Duplicate of #330
See also #417

**Comment by dpjohnst** [comment] 2020-12-04 06:20
Closing this issue as it's a duplicate of #330 - feel free to head over to that issue and subscribe to it for status updates.

**Closed by dpjohnst** 2020-12-04 06:20 UTC
