### ISSUE TITLE
add file to gitignore

### ISSUE THREAD

**Issue by paulowens** [sublimehq/sublime_merge#1764] opened 2023-06-07 10:39 UTC
**Problem description**

A description of a problem, workflow or integration that your suggestion would solve. If the problem is OS-specific, include that information here.

**Preferred solution**

A description of what changes should be made to Sublime Merge to solve the problem.

**Alternatives**

A description of any alternative solutions or enhancements considered.

**Screenshots**

If applicable, add screenshots to help demonstrate the problem or proposed solution. This section may be omitted/removed.

**Comment by dpjohnst** [comment] 2023-06-13 06:57
Hi @paulowens,

Thanks for sharing your feedback!

I'm going to go ahead and close this, as it's a duplicate of an existing issue: https://github.com/sublimehq/sublime_merge/issues/110

Feel free to comment any additional feedback that you don't see reflected in the issue/comments listed above.

(Also for future bug reports/feature requests: it's really valuable if you can fill out the template (including a full problem/feature description).

Cheers,
\- Dylan from Sublime HQ

**Closed as completed by dpjohnst** 2023-06-13 06:57 UTC
