### ISSUE TITLE
Prevent loss of unsaved commit message changes when clicking away to another commit

### ISSUE THREAD

**Issue by Aligorith** [sublimehq/sublime_merge#1317] opened 2021-11-03 02:59 UTC
**Problem description**

With Sublime Merge 3, build 2059

When editing the commit message of an existing commit ("A"), if you accidentally click on another commit ("B") in the list/graph (e.g. to copy some text from that other commit's log message) when you return to the original commit being edited ("A") to continue editing the message, any WIP changes you'd made to the commit message (before pressing "Save") will be lost and unrecoverable.

This is unexpected and causes data loss (especially if the changes were more substantial than just fixing a few typos).

I've been bitten by this a few times while editing merge commit messages to feature change logs of the changes the branch being merged contains.

**Preferred solution**

Save the edited commit message to a buffer somewhere, and restore it when they click back on that commit, with the commit message editing widget open, ready for the user to continue editing the commit message as if they hadn't clicked away.

**Alternatives**

**V1)** Prevent the user clicking away - asking them to either save their changes or cancel first.

**V2)** When a commit message is being edited, automatically press "Save" on the edited commit message if the user clicks away to another commit (especially if significant changes have been made to the commit message). Only discard changes if the user clicks "Cancel" explicitly.

> This option is less preferred as you might accidentally clobber an old commit's log message, then trying to click away to cancel it. So, it's probably best to not do it this way.

**Comment by srbs** [comment] 2021-11-03 05:32
duplicates: #1069

**Comment by dpjohnst** [comment] 2021-11-05 05:38
Hi @Aligorith,

Thank you for the detailed report - much appreciated!

As @srbs has noted, this is a duplicate of issue #1069 and #486 
I'm going to close this issue, but please feel free to head over to the linked issues and subscribe to them.

Regarding the issue - this is a high-priority issue for the team and we are actively working to resolve this.

Cheers,
\- Dylan

**Closed by dpjohnst** 2021-11-05 05:38 UTC
