### ISSUE TITLE
Sublime Merge loses the previously set window size.

### ISSUE THREAD

**Issue by mvlc** [sublimehq/sublime_merge#396] opened 2019-02-21 19:19 UTC
**Version info**

 - OS: macOS 10.14.3
 - Build: 1104

**Description**

Sublime Merge loses the previously set window size after CMD+W followed by CMD+Q.
It also happens when Sublime Merge isn't open and starts from the Sublime Text statusbar.

**Steps to reproduce**

First case:
1. Open Sublime Merge
2. CMD+W
3. CMD+Q.
4. The previously set window size is lost.

Second case:
1. Sublime Merge app isn't open.
2. Open Sublime Text.
3. Open Sublime Merge from the Sublime Text statusbar.
4. The previously set window size is lost.

**Expected behavior**

Remember the previously set window size.

**Comment by simonbates** [comment] 2019-03-17 14:03
I'm also seeing the second case (opening Sublime Merge from Sublime Text) on Windows 10.

- Windows 10 version 1809
- Sublime Merge: 1107
- Sublime Text: 3200

**Comment by rahulk94** [comment] 2019-06-17 22:50
This bug also occurs when launching Sublime Merge from the cli utility 
```
# inside a directory with a .git folder 
$ smerge .
```
Tested with Build 1116.

**Comment by ndeloof** [comment] 2019-11-05 14:34
same issue on Linux. I'm using sublime merge as git mergetool, and it always open with default size which is pretty inacurate for my widescreen display

**Comment by chrisjbillington** [comment] 2019-11-27 20:28
I'm seeing this too on Arch Linux (under Xorg, haven't checked on Wayland). 

The problem also presents itself when running Sublime Merge from Sublime Text with "Sublime Merge: Open Repository", which presumably runs `smerge <repo_folder>` under the hood.

It's not just the window size that is forgotten, it's all of the window geometry such as whether the side pane is visible, the sizes of the three panes, and whether "locations" or "contents" are shown in the side pane:


![out](https://user-images.githubusercontent.com/1044087/69757205-5fb1ae00-112a-11ea-8695-df044cbd7899.gif)

**Comment by eantonya** [comment] 2020-04-22 16:09
This seems like a pretty important bug to fix. Makes it a lot less pleasant to use ST3 and Sublime Merge together.

**Comment by dpjohnst** [comment] 2020-10-13 05:38
Hi all,

The `smerge` issue has been fixed in Sublime Merge Build 2035.
The original issue is still under active investigation, and I'll provide an update as we investigate further.

Thanks,
\- Dylan

**Comment by frou** [comment] 2020-10-31 20:46
@dpjohnst With build 2038 on macOS 10.15, it's no different for me. Steps:

1. Open a repo from the terminal using `smerge .`
2. Resize the Sublime Merge window to be larger, by dragging its corner with the mouse.
3. Quit Sublime Merge using Cmd-Q
4. Open the repo again from the terminal using `smerge .`
5. The window is back to being small again.

**Comment by dpjohnst** [comment] 2020-11-25 07:48
Hi all,

This should be all resolved in Sublime Merge Build 2041 (development build), and will be available in the next stable build.
Let me know if you are still seeing the issue, and we can investigate further.

Kind regards,
\- Dylan

**Comment by bakerkretzmar** [comment] 2020-11-25 17:42
Just downloaded the new dev build, it's fixed for me when _not_ opening Sublime Merge via the command line, but I'm still seeing this issue using `smerge .`.

macOS 10.15.7
Build 2041

**Comment by 1nv** [comment] 2020-12-07 12:53
@dpjohnst 
With 2041, Sublime Merge stopped remembering maximized window state when opening it through 'sublime_merge.exe' shortcut on Windows 10 1903.

**Comment by jaraco** [comment] 2021-01-15 17:25
> Just downloaded the new dev build, it's fixed for me when _not_ opening Sublime Merge via the command line, but I'm still seeing this issue using `smerge .`.

Same for me. And importantly, this workflow is the one I use when using `git mergetool`, so is my main workflow for interacting with Sublime Merge, so the issue is essentially unfixed for my case.

**Comment by bakerkretzmar** [comment] 2021-01-29 16:55
Confirming this issue is still present using `smerge` in build 2042.

**Comment by dpjohnst** [comment] 2021-02-03 10:49
This has been resolved in Sublime Merge build 2043 - let me know if you're still seeing this issue and we can investigate further.

**Comment by bakerkretzmar** [comment] 2021-02-03 15:01
Works great for me now, thanks!

**Comment by dpjohnst** [comment] 2021-02-23 22:37
Hi all,

Just confirming that the fix for this issue was released to the stable channel (Build 2047).
I'll be closing this issue now, but please feel free to reach out if you're still affected by this issue.

Cheers,
\- Dylan

**Closed by dpjohnst** 2021-02-23 22:37 UTC
Labels: S: minor, bug

**Comment by dsl101** [comment] 2021-07-05 10:13
This issue still appears to be there on Windows 10 SM build 2057. Running from a pinned taskbar entry, setting window size / location, then closing, and then running from command line with `smerge.exe .` or from the ST3 status bar loses all previous opened repos, and the window is a different size and on a different monitor to where it was last opened for me.

If the pinned taskbar 'instance' is already opened with a repo that is then opened via command line or ST3, a new SM window is created with the 'repo chooser' dialog, as well as activating the existing window / repo, but that might be a separate issue.

**Comment by mynetx** [comment] 2024-07-18 07:23
Also see #1050
