### ISSUE TITLE
Search in command palette is behaving very strangely

### ISSUE THREAD

**Issue by ghost** [sublimehq/sublime_merge#663] opened 2020-02-14 14:47 UTC
**Version info**

 - OS: macOS Catalina
 - Build: 1202 dev channel

**Description**

When I press Cmd+P and I type to find a command, focus often jumps to `About`, even when my search is not at all related to About.

**Steps to reproduce**

1. Open Sublime Merge
2. Press Cmd+P to open Command Palette
3. Type `dele`

**Expected behavior**

Focus is on `Delete Branch` or something like that.

**Actual behavior**

Focus is on `About`.

**Screenshots**

![ezgif-3-6273b4f80d2f](https://user-images.githubusercontent.com/48212627/74541001-16127b80-4f41-11ea-800d-7c8e181335ef.gif)

**Comment by willrowe** [comment] 2020-02-18 16:18
This is a fairly significant issue for me, especially when deleting branches or other possibly destructive actions. It is happening when filtering branches, so when I type in `mas` for `master`, it initially looks like it is going to select the `master` branch, but then selects another branch at the last second right before I hit the enter key and it is too late.

**Comment by bgeron-contiamo** [comment] 2020-02-20 10:05
Fixed in build 1203 🙌

**Comment by bgeron-contiamo** [comment] 2020-02-20 10:06
oops it was my other issue that was fixed

**Comment by bgeron-contiamo** [comment] 2020-03-06 14:04
Still present in build 2000, but congrats on the redesign! It looks awesome!

**Comment by willrowe** [comment] 2020-05-19 12:27
To confirm, this is still an issue.

**Comment by bgeron-contiamo** [comment] 2020-05-19 12:51
@bgeron

**Comment by dpjohnst** [comment] 2020-05-25 00:22
Hi all,

Thank you for you patience while we investigated this issue.
Some good news - we've got a fix for this coming in the next build!

Thanks,
\- Dylan

**Comment by bgeron** [comment] 2020-05-25 06:58
Thank you! I’m very excited!

Cheers, Bram

Am Mo, 25. Mai 2020, um 02:23, schrieb Dylan Johnston:

**Comment by willrowe** [comment] 2020-05-27 12:54
I can confirm that this has been fixed in build 2020.

**Comment by bgeron** [comment] 2020-05-27 15:10
+1. Was a bit tricky to install as I'm on the dev channel (which doesn't contain build 2020 yet), but I figured out on Ubuntu you can just add both channels to always get the newest version.

**Closed** 2020-06-09 06:24 UTC
