### ISSUE TITLE
Allow multiselect on Files for bulk operations

### ISSUE THREAD

**Issue by AntonPetrov83** [sublimehq/sublime_merge#1150] opened 2021-05-19 08:21 UTC
**Problem description**

Now to discard some files from the list I have to pick them one by one.

**Preferred solution**

Allow to use Ctrl or Shift with LMB to select multiple files to do bulk operations on them: staging and discard. See how it is implemented in Sourcetree.

**Sourcetree**

![image](https://user-images.githubusercontent.com/1997978/118780095-5f642000-b894-11eb-9c11-ec64c80c2aa5.png)

**Comment by srbs** [comment] 2021-05-19 08:48
duplicates #381
related: #143, #461, #382

**Comment by dpjohnst** [comment] 2021-05-31 05:47
Hi @AntonPetrov83,

Thanks for sharing this feedback - appreciated!

As @srbs mentioned, this is a duplicate of #381 so I'm going to go ahead and close this issue.
Please feel free to subscribe to (or comment on) the linked issue to ensure you receive any updates/announcements on the issue!

Thanks,
\- Dylan

**Closed by dpjohnst** 2021-05-31 05:47 UTC
