### ISSUE TITLE
"Show Git Output" windows can become wider than the screen

### ISSUE THREAD

**Issue by haferburg** [sublimehq/sublime_merge#554] opened 2019-08-09 16:09 UTC
**Version info**

 - OS: Windows 10 x64
 - Build: 1116

**Description**

I run `git p4` from within Sublime Merge. Some of the command output can be very wide. In one example I had output where a line had 227 characters. This results in the output window being wider than the screen, resulting in text appearing cut off left and right.

It would be nice if the output window width would become constrained to the screen. If the text is too long, it would be nice if a horizontal scrollbar would appear.

As a workaround I can copy the text and paste it into an editor.

**Comment by srbs** [comment] 2019-08-16 17:11
duplicate of #538

**Closed** 2019-08-16 21:45 UTC
