### ISSUE TITLE
Making TAGS visible also makes hidden branches visible (build 2034)

### ISSUE THREAD

**Issue by CheyenneWills** [sublimehq/sublime_merge#932] opened 2020-09-28 17:23 UTC
**Version info**

 - OS: Gentoo Linux (upto date)
 - Build: 2034

**Description**

Making all TAGS visible (e.g. Clicking on "TAGS") shows hidden branches (clicking on TAGS again hides the hidden branches)

In addition, left clicking on the branch does not show a way to "rehide" the branch

**Steps to reproduce**

1. Open repository ...
2. make one branch visible
3. Click on "TAGS"  in the location panel

**Expected behavior**

When clicking on TAGS in the Location panel only tags within the visible branches should be shown

TAGS unclicked, only one branch has been marked visible (the remote Centos/centos8)
![shot-2020-09-28_11-11-59](https://user-images.githubusercontent.com/9040862/94464638-f2bcd980-017b-11eb-94c1-f04f091f8b3b.jpg)

Clicking on TAGS, the master branch is now visible -- the tag V5.9-rc6 is only in the master branch (also scrolled back to the top of the list of commits) 
![shot-2020-09-28_11-12-49](https://user-images.githubusercontent.com/9040862/94464639-f3ee0680-017b-11eb-840f-c2359ab8ea93.jpg)

**Comment by dpjohnst** [comment] 2020-09-28 23:36
Hi @CheyenneWills,

Thanks for sharing this.

This is actually expected behavior. For the purposes of visibility, tags are now considered roots of the commit graph.
This means that if you have a tag referencing a commit, that commit and all other parents of that commit will be visible if the tag is visible.

Let me know if you have any questions.

Thanks,
\- Dylan

**Comment by CheyenneWills** [comment] 2020-09-28 23:49
Thanks,

Though this has really made the TAGS view useless, as there is now no easy way to re-hide those branches.  The way it used to work was if I clicked on the TAGS it would show the tags that were in the currently visible branches.  With the new way, if I'm working on a particular release branch and I click on the TAGS --all-- the release branches (as well as any custom and feature branches that might happen to have a tag) are displayed.

**Comment by dpjohnst** [comment] 2020-09-29 00:12
Hi @CheyenneWills,

Thanks for sharing this additional information.

Perhaps then adding a dedicated indicator of which tags are part of a branch would be useful for you? 
If so, I'd definitely suggest submitting a feature request for this (I can't see any existing ones).

Thanks,
\- Dylan

**Comment by dpjohnst** [comment] 2020-09-30 06:02
Thanks @CheyenneWills,

I'm going to go ahead and close this issue for the reasons mentioned above, but we can definitely move over to the other request for further discussion.

Thanks,
\- Dylan

**Closed by dpjohnst** 2020-09-30 06:02 UTC

**Comment by CheyenneWills** [comment] 2020-09-30 15:38
> Thanks @CheyenneWills,
> 
> I'm going to go ahead and close this issue for the reasons mentioned above, but we can definitely move over to the other request for further discussion.
> 
> Thanks,
> - Dylan

That's fine

**Comment by g667** [comment] 2025-07-31 07:40
Hi @CheyenneWills,

it's absolutely understandable what you are saying. It matches exactly how Git technically works. Unfortuanetly the good design of how git handles roots and what git handles as root, does not match the way you as a user required filtered information when using git.

Please think about e.g. a multi version project with currently a dozen of parallel maintained versions, each version on its own release branch and of course with own, multiple version tags. Now think about the size of the commit tree, when you want to investigate the commits between tag x and x+1 from your 5th latest version. It will be not possible to detect visually the commits in subject, because you see multiple parallel commit graphs and sublime merge does not give you the possibilty to filter them, as you would do in each console by "git log abcdef..xyz123". And this is only a quick overview of the problem.

One more thing: Would you also argument that way, when someone displays data from a database purely in a way like they are stored? Would you say the Entity-Relation-Ship is designed within the database this way, so we display the data intentionally? Sure you get the point ;-)

So please. Understand the use case and differentiate between the technical correctness and the required different view we must have, when we try to fulfill user and use case needs-
