### ISSUE TITLE
After the update, there was an additional serious problem with Korean input.

### ISSUE THREAD

**Issue by yourichng** [sublimehq/sublime_merge#869] opened 2020-08-18 01:10 UTC
Hello

I updated the sublime merge to 2025 today, and confirmed that the Windows IME error was fixed in the history.

However, more serious problems were encountered than before.

Only the first Hangul character is entered, but none are entered.

For example, if you type "test", only "t" is entered, and "est" is no longer entered.

In Korean, if you enter "테스트.", "테." is being entered.

One word becomes more serious from what was put on, so only one letter can be entered.

related issue: https://github.com/sublimehq/sublime_merge/issues/772

**Comment by dpjohnst** [comment] 2020-08-18 23:28
Hi @yourichng,

Thank you for reporting this issue.

Could you try updating to Sublime Merge 2027 when you have a chance, and confirm whether the issue is resolved.

Kind regards,
\- Dylan

**Comment by yourichng** [comment] 2020-08-19 00:57
@dpjohnst 

![image](https://user-images.githubusercontent.com/2605918/90579880-4e518a00-e202-11ea-975a-ca4664df863c.png)

I'm already using build 2027.

**Comment by joongtang** [comment] 2020-08-27 00:05
I have same issue.

**Comment by joongtang** [comment] 2020-08-27 00:16
![Honeycam 2020-08-27 09-11-58](https://user-images.githubusercontent.com/6409795/91368988-79ad2800-e845-11ea-93f9-55a245e5757e.gif)

and when using Windows Touch Keyboard, predictive text is not entered and disappeared.

**Comment by dpjohnst** [comment] 2020-09-07 03:26
CC'ing you in here @BenjaminSchaaf

**Comment by BenjaminSchaaf** [comment] 2020-09-14 02:13
The predictive text is a separate issue. This issue seems to be the same as https://github.com/sublimehq/sublime_text/issues/3626. I'll keep this open for the predictive text issue.

**Comment by yourichng** [comment] 2020-09-17 04:02
My current issue is

It seems to have been resolved in Windows version 2004 (OS Build 20215.1000).

![image](https://user-images.githubusercontent.com/2605918/93418704-eb790e80-f8e5-11ea-87c2-ccd4202399c7.png)

**Comment by dpjohnst** [comment] 2020-09-25 08:58
Hi all,

Thank you for your patience while this issue has been resolved.

This issue should be resolved in development build 2034.

For those on the development channel, please confirm whether the issue has been resolved on your end.

Thanks,
\- Dylan

**Comment by uOOOO** [comment] 2020-09-26 13:54
It's working on Windows10 2004(19041.508)

**Closed** 2020-10-12 13:32 UTC
Labels: bug
