### ISSUE TITLE
Multi-Selection in File panel

### ISSUE THREAD

**Issue by CloudAktsk** [sublimehq/sublime_merge#1215] opened 2021-07-19 02:31 UTC
**Problem description**

If I have 20 modified files and I want to reset 10 of them, the only way I can do this is by right click on each file and choose "discard" from the context menu.

**Preferred solution**

Please add multi-selection feature in the "File" panel.
So that user can select multiple files by `shift + left click(for range)` or `ctrl + left click(for adding one file)` and then right-click to do action on all selected files.

**Screenshots**
The file panel
![image](https://user-images.githubusercontent.com/39080633/126094415-aa7884b5-46c4-4fa9-837d-496930e02f43.png)

**Comment by srbs** [comment] 2021-07-19 04:38
duplicates: #381
related: #418, #143, #461
see also: #382, #689

**Comment by dpjohnst** [comment] 2021-07-19 23:58
Hi @CloudAktsk,

Thanks for sharing this feedback with the team!

As this is a duplicate of an existing issue, I'm going to go ahead and close this one to keep everything consolidated.

Feel free to head over to the issue that @srbs has linked above and give it a thumbs up / subscribe.

Cheers,
\- Dylan

**Closed by dpjohnst** 2021-07-19 23:58 UTC

**Comment by hkchakladar** [comment] 2022-08-31 14:41
Issue dead?
