### ISSUE TITLE
Rename file matching incorrectly shown, correct in git

### ISSUE THREAD

**Issue by qgates** [sublimehq/sublime_merge#906] opened 2020-09-08 13:04 UTC
**Version info**

 - OS: Windows 10
 - Build: 2032

**Description**

When a file is renamed and a few other files are added, upon staging SM incorrectly suggests the file has been renamed to one of the newly added files.

**Steps to reproduce**

1. File is renamed in project, appears unstaged in SM as a delete followed by add. In this example `psql-bookingsys` has been renamed to `psql-okbook`
2. Add a few other (similar) files.
3. Stage everything.
4. SM incorrectly shows `psql-bookingsys` has been renamed to one of the newly added files

See pics which best illustrate the problem.

**Expected behavior**

Should show correct renaming as `git status` does.

Interestingly, staging in SM and checking with `git status` still shows correct renaming. Also, once committed with SM, `git diff` shows correct renaming too. So the problem is more about what SM displays than what's actually going on under the hood.

**Screenshots**

![image](https://user-images.githubusercontent.com/4213509/92478957-d3650900-f1da-11ea-999f-c8660ea13bf6.png)

![image](https://user-images.githubusercontent.com/4213509/92478984-dd870780-f1da-11ea-91b7-b9215dd7d0e3.png)

**Comment by srbs** [comment] 2020-09-08 17:39
probably a duplicate of #384

**Comment by dpjohnst** [comment] 2020-09-08 23:32
Hi @qgates,

Thank you for sharing your feedback with us.

As rename detection is based on a file similarity heuristic, it doesn't always match what we expect. As Git has its own unique heuristic, there will always be cases where Git may not match with Sublime Merge.

Rest assured that this is purely for UX purposes, and won't affect the contents of the resulting commit (all our write operations are done with Git).

What's happened here is one of the newly created files had a higher similarity score, and has been marked as a rename. If you feel like this is erroneous (the file is completely different), let me know and I can investigate further.

Thanks,
\- Dylan

**Comment by dpjohnst** [comment] 2020-09-13 23:45
Hi @qgates,

I'm going to go ahead and close this issue, as it's a quirk of having to use a unique heuristics-based approach to rename detection. Please don't hesitate to re-open if you feel this issue deserves more investigation that isn't covered in the comment above.

Thanks,
\- Dylan

**Closed by dpjohnst** 2020-09-13 23:45 UTC
Labels: wontfix
