### ISSUE TITLE
Merge does not respect side bar setting when opening a new repository

### ISSUE THREAD

**Issue by facelessuser** [sublimehq/sublime_merge#1043] opened 2021-01-21 15:44 UTC
**Version info**

 - OS: macOS Big Sur, Windows 10
 - Build: 2041

**Description**

I have the layout setting set to `One Column`. But whenever I open a new git repo for the first time, 
it defaults to 3 columns. I have to physically change the setting from 1 column layout to another layout and then back to 1 column, or I have to restart Merge to get to render with 1 column. After that, it will remember the layout even when switching between repos.

**Steps to reproduce**

1. Set layout to the 1 column layout.
2. Open a brand new, never before seen repo
3. Notice the layout is not respected

**Expected behavior**

I would expect if the global option is set to a single column for the sidebar that all new projects would initialize the layout properly and not require a restart or toggling of the layout to get it to properly respect the preferred layout.

**Screenshots**

The description should be sufficient.

**Comment by dpjohnst** [comment] 2021-01-21 23:19
Hi @facelessuser,

Thanks for reporting this issue - this seems to be a duplicate of: https://github.com/sublimehq/sublime_merge/issues/1020
We've got a fix for this in the works an I'll keep you updated on the linked issue (feel free to subscribe to it).

I'm going to go ahead and close this issue.

Kind regards,
\- Dylan

**Closed** 2021-01-21 23:19 UTC
