### ISSUE TITLE
Ability to alias repos

### ISSUE THREAD

**Issue by DavidKittleSEL** [sublimehq/sublime_merge#1218] opened 2021-07-20 22:38 UTC
**Problem description**

I would like to be able to alias repositories. for instance if a clone a repo down to my machine called "snowflake-windows-gui-app", I might alias it as something like "win-gui".

**Preferred solution**

Be able to alias a repo, perhaps by right clicking on the repo tab and selecting "Alias"

**Alternatives**

I'm open to suggestions

**Comment by dpjohnst** [comment] 2022-03-03 02:49
Thanks for sharing this feedback!

I'm going to close this one, as it's a duplicate of https://github.com/sublimehq/sublime_merge/issues/1134

**Closed by dpjohnst** 2022-03-03 02:49 UTC
