### ISSUE TITLE
Sublime Merge crashing on Big Sur

### ISSUE THREAD

**Issue by giladshanan** [sublimehq/sublime_merge#1030] opened 2021-01-07 16:29 UTC
**Version info**

 - OS: macOS 11.1 (Big Sur)
 - Build: 2039

**Description**

I just set up a new laptop, MacBook Pro (16-inch, 2019) running Big Sur, and installed Sublime Merge. The app worked fine until I rebooted, and now after a brief moment Sublime Merge crashes with no error message. I'm not sure how to get more info to do more debugging.  I tried rebooting the laptop again, and also tried removing and reinstalling Sublime Merge.  

**Steps to reproduce**

1. Open Sublime Merge
2. Sublime Merge crashes (closes with no error message)

**Expected behavior**

The application starts

**Comment by giladshanan** [comment] 2021-01-07 20:24
I downloaded dev build 2041 from https://www.sublimemerge.com/dev, and that is running fine.

**Comment by dpjohnst** [comment] 2021-01-11 01:45
Hi @giladshanan,

Glad to hear it's resolved for you in build 2041!

We've fixed several bugs for MacOS between build 2039 and build 2041 - it's likely one of these fixes has resolved the issue.
All of these fixes will be available in the next stable build.

If you find that the issue is not resolved in the next stable build, please don't hesitate to reach out again.

Kind regards,
\- Dylan

**Closed** 2021-01-29 05:24 UTC
Labels: bug

**Comment by giladshanan** [comment] 2021-01-29 15:59
Just an update that today I restarted my laptop and was met with the same problem.  I deleted and upgraded to build 2042, and now all is well again.

**Comment by giladshanan** [comment] 2021-02-05 15:15
I was prompted to download a new stable version today.  After installing the app no longer opens (same issue as before).
