### ISSUE TITLE
Save column size after restarting Sublime Merge / open a new window

### ISSUE THREAD

**Issue by j0k3r** [sublimehq/sublime_merge#66] opened 2018-10-05 08:49 UTC
**Problem description**

You can easily resize the 3 columns within the app:
- the one with branches, remotes, tags & stashes
- the one with commit tree
- and the one with the working directory

Once I resized these columns if I open a new repository or close the whole app and reopen, the resize isn't kept.

Resized:
![image](https://user-images.githubusercontent.com/62333/46525508-177f5e80-c88c-11e8-9e2d-e08cceb3396b.png)

After restarting:
![image](https://user-images.githubusercontent.com/62333/46525562-341b9680-c88c-11e8-8a1a-380e21e69e29.png)

**Preferred solution**

Save resize upon restart / new window.
Maybe using a preference like `keep_column_resize: true/false`

**Alternatives**

No alternative.

**Comment by onecrayon** [comment] 2018-10-05 15:50
This is possibly a duplicate of #26 (or a more generic description of the same problem).

**Closed** 2018-10-05 19:14 UTC
