### ISSUE TITLE
Modified Files Hover tooltip gets stuck

### ISSUE THREAD

**Issue by orrin** [sublimehq/sublime_merge#891] opened 2020-08-27 23:30 UTC
**Version info**

 - OS: Windows 10
 - Build: 2032

**Description**

The hover tooltip shown in the modified files list will sometimes stick and not go away.  New tooltips will continue to show when moving the mouse over other list items.  The tooltip will stay visible until I restart the application.

This is an intermittent issue that I cannot replicate at will.  It has been happening every couple of weeks for at least the past 6 months.

**Steps to reproduce**

1. Open repository ...
2. Modify some files if there aren't any
3. view the Modified Files list
4. move your mouse over the list of files

**Expected behavior**

Tooltip disappears when exiting hover.

**Screenshots**

![Untitled](https://user-images.githubusercontent.com/2020631/91504184-3b355e80-e881-11ea-8f7f-86a38250b0c5.png)

**Comment by dpjohnst** [comment] 2020-08-28 02:26
Hi @orrin,

Thank you for reporting this issue. This is actually a duplicate of issue #753, so I'm going to go ahead and close this issue.
Please feel free to subscribe to issue #753 to ensure you continue to receive updates regarding the issue.

Thanks,
\- Dylan

**Closed by dpjohnst** 2020-08-28 02:26 UTC
