### ISSUE TITLE
Always use commit message of editing commit

### ISSUE THREAD

**Issue by RanceZero** [sublimehq/sublime_merge#350] opened 2019-01-18 11:01 UTC
Sometimes in my workflow I am thinking of doing a commit and so start writing its commit message, then, decide to edit a previous commit, but when I am about to recommit this previous commit I see the commit message is not of the commit I am editing but from the one I was doing before. I do not know if this is the only occasion where a previous commit message gets stick when it should not, but is an example of some that does.
Maybe my workflow is the wrong one here, but I have countless times found myself commiting edits with a commit message that was not from that commit, and this is troublesome.

**Comment by CheyenneWills** [comment] 2019-01-19 00:38
I just got bit by this as well.  I

**Comment by CheyenneWills** [comment] 2019-04-12 22:35
This is a bug.  I've been bitten again with this problem. 

Editing a commit contents should not result in the commit message being replaced with the message from a different commit.

**Comment by CheyenneWills** [comment] 2019-04-12 23:16
I can easily reproduce this.

1. edit commit A's contents
2. abort rebase
3. edit commit B's contents
4. BUG... the commit message is now set to commit A's commit message.

**Comment by CheyenneWills** [comment] 2019-04-13 01:21
Some more info.

It looks like the aborted commit message becomes "sticky", until a commit actually is saved.  You can "modify" the commit message and as long as you don't save a commit it follows around for any commit edits until a commit is saved.  It also persists across closing the app and starting again

**Comment by BenjaminSchaaf** [comment] 2020-02-14 06:32
I can't reproduce this in dev build 1202

**Comment by RanceZero** [comment] 2021-02-15 03:18
I am not able to reproduce this bug as of build 2039.

**Comment by FichteFoll** [comment] 2021-03-24 21:26
I experienced this exact issue 2 weeks ago on either 2046 or 2048 (can't say for sure since it was the day of 2048's release).

**Comment by RanceZero** [comment] 2021-03-24 22:46
@FichteFoll Should I reopen this issue? Please show a video of issue reproduction or explain me the exact steps you did so that I reproduce it here.

**Comment by FichteFoll** [comment] 2021-03-24 23:53
https://user-images.githubusercontent.com/931051/112398447-8a9f1880-8d04-11eb-81b2-c6176f454840.mp4

**Comment by RanceZero** [comment] 2021-03-25 00:32
@FichteFoll you are correct. Doing the same workflow I reproduced the Issue on build 2049.

**Comment by CheyenneWills** [comment] 2021-03-25 01:10
Slightly different sequence.  Note, the video capture did not pick up the pop-ups.  The sequence is:

Selected commit "A"
edit commit -> edit commit contents  -- followed by clicking "ok" in the pop-up
click on abort rebase (twice)

Selected commit "B"
edit commit -> edit commit contents -- followed by clicking "ok" in the pop-up
click on commit and continue rebase.

End result, Commit "B"'s commit message is replaced with message commit "A" (the aborted rebase).

https://user-images.githubusercontent.com/9040862/112403597-557ad200-8cd4-11eb-80ed-0db1ade3b521.mp4

**Comment by dpjohnst** [comment] 2021-05-05 05:56
Hi all,

This should be resolved as of Sublime Merge Build 2054 (stable).
When you have a spare moment, please confirm that it's been resolved on your end and I can go ahead and close this issue.

Thanks,
\- Dylan

**Comment by CheyenneWills** [comment] 2021-05-05 15:26
> Hi all,
> 
> This should be resolved as of Sublime Merge Build 2054 (stable).
> When you have a spare moment, please confirm that it's been resolved on your end and I can go ahead and close this issue.
> 
> Thanks,
> - Dylan

I was unable to reproduce the problem by following the steps I listed above (using sublime merge build 2052).  

So I believe that the issue has been corrected.

Thanks
/Cheyenne

**Comment by RanceZero** [comment] 2021-05-14 23:27
Tested both @CheyenneWills and @FichteFoll test steps here on build 2054. Issue was not reproduced. Seems fixed @dpjohnst .

**Closed** 2023-07-13 00:09 UTC
Labels: enhancement, commit dialog
