### ISSUE TITLE
Staged and commited newly added files are not distinguishable

### ISSUE THREAD

**Issue by VipSaran** [sublimehq/sublime_merge#515] opened 2019-06-12 08:34 UTC
**Problem description**

Newly added files are displayed differently (gray) in the list of changes (as part of "Unstaged" section), but once they are staged and/or commited, they are no longer (easily) distinguished from the rest of the changes in the commit.

**Preferred solution**

Newly added files are displayed with different "header" color in the list of changes.
Optionally, they are also easily distinguished in Contents tab.

**Alternatives**

An alternative to a different/distinguishable "header" color would be to add a prefix or a suffix letter/annotation (e.g. "M" for modified, "A" for added, "D" for deleted; or the fully verbose variants) to the "header".

**Screenshots**

Current behavior:
![image](https://user-images.githubusercontent.com/995948/59335370-c1a56500-8cfc-11e9-8473-e61a93c5e606.png)

**Comment by srbs** [comment] 2019-06-12 18:15
Duplicate of #45

**Closed** 2021-10-08 02:56 UTC
