### ISSUE TITLE
Window size not restored on startup if opened with specific directory

### ISSUE THREAD

**Issue by rchl** [sublimehq/sublime_merge#958] opened 2020-10-23 07:56 UTC
**Version info**

 - OS: macOS 10.15
 - Build: 2036

**Description**

When opening SM either with `smerge .` or by clicking the branch name in Sublime Text, the SM opens without restoring the previous session or window size/position.

(I've heard that not restoring session might be intentional but then this bug can be about window size/position if those are separate).

**Steps to reproduce**

1. Open a couple of repositories in SM so that there are multiple repository tabs open
2. Close SM
3. With some repo opened in Sublime Text, click the branch name in the status bar to open SM

**Expected behavior**

The previously saved window size and position are restored when SM starts up.
Optionally (and preferred by me), restore the previous session also.

Related issues:
https://github.com/sublimehq/sublime_merge/issues/309
https://github.com/sublimehq/sublime_merge/issues/532 (This one talks about having an option for toggling the behavior which I would personally like very much)

**Comment by frou** [comment] 2020-10-31 20:57
Also #396 and #611

**Comment by dpjohnst** [comment] 2020-11-01 23:41
Hi @rchl,

Thanks for the detailed report - much appreciated!

I've discovered that this is indeed a duplicate of issue #396 - I'm going to go ahead and close this issue, but I'll be posting updates on the issue via #396.

Cheers,
\- Dylan

**Closed by dpjohnst** 2020-11-01 23:41 UTC
Labels: bug
