### ISSUE TITLE
Option to sort the Checkout Branch list by recently used

### ISSUE THREAD

**Issue by cassapula** [sublimehq/sublime_merge#1629] opened 2022-10-21 20:01 UTC
**Problem description**

When working on large projects with a lot of collaborators, the view of the branches when you click for check-out / navigate branch can get kind of messy.

You need to search for the branch you want or remember the name to type it in the search box.

**Preferred solution**
An option to sort the branches by the latest active branch, the same as GitHub for Desktop does. That way, you can easily navigate by your latest used branches.

**Comment by srbs** [comment] 2022-10-23 07:44
duplicate: #1393
related: #1612

**Comment by dpjohnst** [comment] 2022-11-04 00:06
Hi @cassapula,

Thanks for sharing this feedback with us!

As mentioned, this is a duplicate of #1393 and so I'll go ahead and close this.

Kind regards,
\- Dylan from Sublime HQ

**Closed by dpjohnst** 2022-11-04 00:06 UTC
